const assetTrackingData = {
  infoData: {},
  analytics: {},
  notifications: {
    assetTracking: [
      {
        id: "lght1",
        title: "Asset Check-in Recorded",
        subTitle: "Storage Room A.",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75555358586086,
          lng: -105.01657322197286,
        },
      },
      {
        id: "lght2",
        title: "Asset Check-out Recorded",
        subTitle: "Workshop B.",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75729624533388,
          lng: -104.9895572496697,
        },
      },
      {
        id: "lght3",
        title: "Asset Movement Detected",
        subTitle: "Production Area C",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75932453116013,
          lng: -105.01244836237774,
        },
      },
      {
        id: "lght4",
        title: "Asset Located In Designated Area",
        subTitle: "Warehouse D",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75986730174264,
          lng: -105.00059403615393,
        },
      },
      {
        id: "lght5",
        title: "Asset Maintenance Completed",
        subTitle: "Area E",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75181100420289,
          lng: -105.01129637456289,
        },
      },
      {
        id: "lght6",
        title: "Asset Transfer Initiated",
        subTitle: "Distribution Center F",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75515362500666,
          lng: -104.99609756758628,
        },
      },
      {
        id: "lght7",
        title: "Aset Retrieval Recorded",
        subTitle: "Testing Lab G",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.749147447458455,
          lng: -105.00751795284174,
        },
      },
      {
        id: "lght11",
        title: "Asset Misplacement",
        subTitle: "Zone H",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.755724996944544,
          lng: -105.0073944803513,
        },
      },
      {
        id: "lght12",
        title: "Asset Theft Identified",
        subTitle: "Zone H",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.754096574426356,
          lng: -104.99524286694944,
        },
      },
      {
        id: "lght13",
        title: "Asset Damage Reported",
        subTitle: "Zone J",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.76323809694557,
          lng: -105.00263788550286,
        },
      },
      {
        id: "lght14",
        title: "Asset Loss Reported",
        subTitle: "Building C",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.758410381562285,
          lng: -104.99914476116105,
        },
      },
      {
        id: "lght15",
        title: "Asset Tampering Incident Detected",
        subTitle: "Zone C",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.758267544591504,
          lng: -104.98829377916307,
        },
      },

      {
        id: "lght21",
        title: "Asset Tracking Software Updated",
        subTitle: "Zone B",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75809613983553,
          lng: -104.99754684257915,
        },
      },
      {
        id: "lght22",
        title: "Floodlight Maintenance",
        subTitle: "Checking and repairing floodlights",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.753039507624166,
          lng: -104.9947226143879,
        },
      },
      {
        id: "lght23",
        title: "Asset Movement Detected",
        subTitle: "Zone C",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75458224832903,
          lng: -105.00449593036554,
        },
      },
      {
        id: "lght24",
        title: "Asset Tracking System Data Processing",
        subTitle: "Zone B",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75432512727771,
          lng: -105.00505334382431,
        },
      },
      {
        id: "lght25",
        title: "Asset Tracking Tags Replaced",
        subTitle: "Zone C",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75677237845138,
          lng: -104.99989373019561,
        },
      },
      {
        id: "lght26",
        title: "Asset Tracking System Data Processing Delay",
        subTitle: "Zone H",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75978160140874,
          lng: -104.99776980796267,
        },
      },
      {
        id: "lght28",
        title: "Asset Movement Detected",
        subTitle: "Zone H",
        area: "",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75838685085751,
          lng: -105.00005180275836,
        },
      },
      {
        id: "lght30",
        title: "Asset Tracking System Malfunction",
        subTitle: "Zone A",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "asset",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75722374013964,
          lng: -105.00077442018811,
        },
      },
    ],
  },
};

export default assetTrackingData;
