const dashboardNotification = {
  notifications: {
    events: {
      totalCount: 9,
      eventsList: [
        {
          id: "prk1",
          title: "Vehicle Entered",
          area: "Parking Lot -1 ",
          entity: "LPN: ADL-D21| Sot - 18",
          venue: "",
          category: "parking",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75932453116013,
            lng: -105.01244836237774,
          },
        },
        {
          id: "prk2",
          title: "vehicle Exited",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75986730174264,
            lng: -105.00059403615393,
          },
        },
        {
          id: "eng1",
          title: "Power Restored",
          area: "Zone 2",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75181100420289,
            lng: -105.01129637456289,
          },
          equipment: "Equip - 1",
        },
        {
          id: "eng2",
          title: "Energy Audit Completed",
          area: "Zone 3",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75515362500666,
            lng: -104.99609756758628,
          },
          equipment: "Equip - 2",
        },
        // {
        //   id: "sec1",
        //   title: "Maintenance Completed",
        //   area: "Lobby Area 1",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Events",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.762147447458455,
        //     lng: -105.00751795284174,
        //   },
        //   equipment: "Cam - 1",
        // },
        // {
        //   id: "sec2",
        //   title: "Maintenance In-progress",
        //   area: "Lobby Area 2",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Events",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.75181100420289,
        //     lng: -105.00847214637164,
        //   },
        //   equipment: "Cam - 1",
        // },
        // {
        //   id: "lght1",
        //   title: "WiFi Network Upgraded",
        //   subTitle: "",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Events",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.75555358586086,
        //     lng: -105.01657322197286,
        //   },
        // },
        // {
        //   id: "lght2",
        //   title: "WiFi Password Reset",
        //   subTitle: "",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Events",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.75729624533388,
        //     lng: -104.9895572496697,
        //   },
        // },
      ],
    },
    incidents: {
      totalCount: 7,
      incidentList: [
        {
          id: "prk3",
          title: "Wrong Parking",
          area: "Parking Lot -1 ",
          entity: "LPN: ADL-D21| Sot - 18",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.76323809694557,
            lng: -105.00263788550286,
          },
        },
        {
          id: "prk4",
          title: "Double Parking",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.758410381562285,
            lng: -104.99914476116105,
          },
        },
        {
          id: "prk61",
          title: "Accident Detected",
          area: "Parking Lot - 4 ",
          entity: "LPN: ABL-C31| Sot - 28",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.76146903388253,
            lng: -105.00182251057917,
          },
        },
        {
          id: "prk63",
          title: "Double Parking",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.758186488708766,
            lng: -105.00474075387679,
          },
        },
        {
          id: "eng3",
          title: "High Energy Consumption",
          area: "Building C",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.758267544591504,
            lng: -104.98829377916307,
          },
          equipment: "Equip - 3",
        },
        {
          id: "eng4",
          title: "Water Leakage Detected",
          area: "Building A",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.751982493422706,
            lng: -104.99238147786095,
          },
          equipment: "Equip - 4",
        },
        // {
        //   id: "sec3",
        //   title: "Unauthorized Access",
        //   area: "Lobby Area 2",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Incident",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.7519538545636,
        //     lng: -105.00639113612544,
        //   },
        //   equipment: "Cam - 3",
        // },
        // {
        //   id: "sec4",
        //   title: "Tailgating",
        //   area: "Zone 2",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Incident",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.755724996944544,
        //     lng: -105.0059452053584,
        //   },
        //   equipment: "Cam - 4",
        // },
        // {
        //   id: "lght3",
        //   title: "Low Humidity",
        //   subTitle: "Humidity-20%",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Incident",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.755724996944544,
        //     lng: -105.0073944803513,
        //   },
        // },
        // {
        //   id: "lght4",
        //   title: "High Electricity Consumption",
        //   subTitle: "Light Pole-6",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Incident",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.754096574426356,
        //     lng: -104.99524286694944,
        //   },
        // },
      ],
    },
    alerts: {
      totalCount: 4,
      alertList: [
        {
          id: "prk5",
          title: "Parking Temporarily Unavailable",
          area: "LLA Building 1 ",
          entity: "Parking lot C spot13",
          venue: "",
          category: "parking",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75423942004732,
            lng: -105.00910388162495,
          },
        },
        {
          id: "prk6",
          title: "Entrance Blocked",
          area: "LLA Building 1",
          entity: "Parking lot B spot18",
          venue: "",
          category: "parking",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75883889069712,
            lng: -105.00156021948253,
          },
        },
        {
          id: "eng5",
          title: "Unusual Power Fluctuations Detected",
          area: "Zone B",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.76092426375837,
            lng: -104.99806709514071,
          },
          equipment: "Equip - 5",
        },
        {
          id: "eng6",
          title: "Energy-saving Mode Enabled",
          area: "Zone H",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 39.75509648755221,
            lng: -105.00226627653032,
          },
          equipment: "Equip - 6",
        },
        // {
        //   id: "sec5",
        //   title: "Firewall Alert",
        //   area: "Zone A",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Alerts",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.750953922556664,
        //     lng: -104.99999314775921,
        //   },
        //   equipment: "Cam - 5",
        // },
        // {
        //   id: "sec6",
        //   title: "Maintenance Due",
        //   area: "Lobby Area 2",
        //   entity: "",
        //   venue: "Location",
        //   category: "security",
        //   notificationType: "Alerts",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.7541537127103,
        //     lng: -104.99290173042249,
        //   },
        //   equipment: "Cam - 6",
        // },
        // {
        //   id: "lght5",
        //   title: "Outdoor Lighting Malfunction",
        //   subTitle: "",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Alerts",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.75809613983553,
        //     lng: -104.99754684257915,
        //   },
        // },
        // {
        //   id: "lght123586",
        //   title: "Air Quality Index Alert",
        //   subTitle: "",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Alerts",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.753039507624166,
        //     lng: -104.9947226143879,
        //   },
        // },
        // {
        //   id: "lght7",
        //   title: "New Lighting Installation",
        //   subTitle: "Installing additional lights in the park",
        //   area: "Outdoor",
        //   entity: "",
        //   venue: "Location",
        //   category: "lighting",
        //   notificationType: "Alerts",
        //   timeStamp: "09:41 AM",
        //   location: {
        //     lat: 39.7575679010206,
        //     lng: -105.00685433450045,
        //   },
        // },
      ],
    },
  },
};

export default dashboardNotification;
