const dashboardNotification = {
  notifications: {
    events: {
      totalCount: 9,
      eventsList: [
        {
          id: "prk1",
          title: "Vehicle Entered",
          area: "Parking Lot -1 ",
          entity: "LPN: ADL-D21| Sot - 18",
          venue: "",
          category: "parking",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.014096630027934,
            lng: -79.47521540383975,
          },
        },
        {
          id: "prk2",
          title: "Vehicle Exited",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.013239745072982,
            lng: -79.47535575072835,
          },
        },
        {
          id: "eng9",
          title: "Energy Audit Completed",
          area: "Zone A",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.01302737679545,
            lng: -79.47582697363957,
          },
          equipment: "Equip - 4",
        },
        {
          id: "eng11",
          title: "High Voltage",
          area: "Building C",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.01302737679545,
            lng: -79.47582697363957,
          },
          equipment: "Equip - 3",
        },
        {
          id: "sec1",
          title: "Maintenance Completed",
          area: "Lobby Area 1",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.013191247669306,
            lng: -79.47640581615131,
          },
          equipment: "Cam - 1",
        },
        {
          id: "sec2",
          title: "Maintenance In-progress",
          area: "Lobby Area 2",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.013098293457437,
            lng: -79.47575453126504,
          },
          equipment: "Cam - 3",
        },
        {
          id: "lght1",
          title: "WiFi Network Upgraded",
          subTitle: "Provide faster and more reliable connectivity",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012339057804061,
            lng: -79.47665814208264,
          },
        },
        {
          id: "lght2",
          title: "WiFi Password Reset",
          subTitle: "Outdoor WiFi network has been reset",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Events",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.01253100827048,
            lng: -79.47658000143186,
          },
        },
      ],
    },
    incidents: {
      totalCount: 7,
      incidentList: [
        {
          id: "prk3",
          title: "Wrong Parking",
          area: "Parking Lot -1 ",
          entity: "LPN: ADL-D21| Sot - 18",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012428180574371,
            lng: -79.4765136370769,
          },
        },
        {
          id: "prk4",
          title: "Double Parking",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.011771204307172,
            lng: -79.47691596842526,
          },
        },
        {
          id: "prk61",
          title: "Accident Detected",
          area: "Parking Lot - 4 ",
          entity: "LPN: ABL-C31| Sot - 28",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.011641398371088,
            lng: -79.47636075116453,
          },
        },
        {
          id: "prk63",
          title: "Double Parking",
          area: "Parking Lot -3 ",
          entity: "LPN: 510-IBD | Spot - 05",
          venue: "",
          category: "parking",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.011151314308657,
            lng: -79.47718955374224,
          },
        },
        {
          id: "eng18",
          title: "Water Leakage",
          area: "Zone A",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012641522295905,
            lng: -79.47611316803638,
          },
          equipment: "Equip - 3",
        },
        {
          id: "eng19",
          title: "Power Outage",
          area: "Building A",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012316237659237,
            lng: -79.47588602962621,
          },
          equipment: "Equip - 1",
        },
        {
          id: "sec11",
          title: "Unauthorized Access",
          area: "Lobby Area 2",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012852894223169,
            lng: -79.47643593337148,
          },
          equipment: "Cam - 1",
        },
        {
          id: "sec12",
          title: "Tempering Alarm",
          area: "Zone 2",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012971875690903,
            lng: -79.47633805240592,
          },
          equipment: "Cam - 4",
        },
        {
          id: "lght12",
          title: "High Electricity Consumption",
          subTitle: "Light Pole-1",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012950031312087,
            lng: -79.47579712394808,
          },
        },
        {
          id: "lght13",
          title: "Hazardous AQI",
          subTitle: "AQI-200, Light Pole-3",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Incident",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012748759453942,
            lng: -79.47590201481266,
          },
        },
      ],
    },
    alerts: {
      totalCount: 4,
      alertList: [
        {
          id: "prk5",
          title: "Parking Temporarily Unavailable",
          area: "LLA Building 1 ",
          entity: "Parking lot C spot13",
          venue: "",
          category: "parking",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.010871706435426,
            lng: -79.47682753009195,
          },
        },
        {
          id: "prk6",
          title: "Entrance Blocked",
          area: "LLA Building 1",
          entity: "Parking lot B spot18",
          venue: "",
          category: "parking",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012501191964672,
            lng: -79.4757609694814,
          },
        },
        {
          id: "eng29",
          title: "Unusual Power Fluctuations",
          area: "Zone A",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.01261011551617,
            lng: -79.47630850706913,
          },
          equipment: "Equip - 3",
        },
        {
          id: "eng30",
          title: "Energy-Saving Mode Enabled",
          area: "Zone H",
          entity: "",
          venue: "",
          category: "energy",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012444108206523,
            lng: -79.47646750395624,
          },
          equipment: "Equip - 2",
        },
        {
          id: "sec21",
          title: "Firewall Alert",
          area: "Zone A",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012902729599116,
            lng: -79.47614698721398,
          },
          equipment: "Cam - 2",
        },
        {
          id: "sec22",
          title: "Maintenance Due",
          area: "Lobby Area 2",
          entity: "",
          venue: "Location",
          category: "security",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.013221642232894,
            lng: -79.47610214005243,
          },
          equipment: "Cam - 4",
        },
        {
          id: "lght21",
          title: "Outdoor Lighting Malfunction",
          subTitle: "Maintenance team notified",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012014708174505,
            lng: -79.47630359698356,
          },
        },
        {
          id: "lght22",
          title: "Floodlight Maintenance",
          subTitle: "Checking and repairing floodlights",

          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012032467496711,
            lng: -79.47597693686244,
          },
        },
        {
          id: "lght23",
          title: "Lighting Fixture Replacement",
          subTitle: "Replacing faulty fixtures in the building",
          area: "OutDoor",
          entity: "",
          venue: "Location",
          category: "lighting",
          notificationType: "Alerts",
          timeStamp: "09:41 AM",
          location: {
            lat: 9.012032467496711,
            lng: -79.47610280589993,
          },
        },
      ],
    },
  },
};

export default dashboardNotification;
