const energyManagementData = {
  infoData: {},
  analytics: {},
  notifications: {
    energyManagement: [
      {
        id: "eng1",
        title: "Power Restored",
        area: "Zone 2",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.74858537445075,
          lng: -104.9990281184832,
        },
        equipment: "Equip - 1",
      },
      {
        id: "eng2",
        title: "Energy Audit Completed",
        area: "Zone 3",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.748820807009096,
          lng: -105.00765307248454,
        },
        equipment: "Equip - 2",
      },
      {
        id: "eng3",
        title: "Gas Leak Detected",
        area: "Building C",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75239143550776,
          lng: -105.00423371202247,
        },
        equipment: "Equip - 3",
      },
      {
        id: "eng4",
        title: "Water Leakage Detected",
        area: "Building A",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75203830467224,
          lng: -104.99428184202094,
        },
        equipment: "Equip - 4",
      },
      {
        id: "eng5",
        title: "Unusual Power Fluctuations Detected",
        area: "Zone B",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.751345721842526,
          lng: -104.9996278180246,
        },
        equipment: "Equip - 5",
      },
      {
        id: "eng6",
        title: "Energy-saving Mode Enabled",
        area: "Zone H",
        entity: "",
        venue: "",
        category: "energy",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.749712559703354,
          lng: -104.99568287315347,
        },
        equipment: "Equip - 6",
      },
    ],
  },
};

export default energyManagementData;
