const lightingData = {
  infoData: {},
  analytics: {},
  notifications: {
    lighting: [
      {
        id: "lght1",
        title: "WiFi Network Upgraded",
        subTitle: "Provide faster and more reliable connectivity",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75555358586086,
          lng: -105.01657322197286,
        },
      },
      {
        id: "lght2",
        title: "WiFi Password Reset",
        subTitle: "Outdoor WiFi network has been reset",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75729624533388,
          lng: -104.9895572496697,
        },
      },
      {
        id: "lght3",
        title: "WiFi Signal Boost",
        subTitle: "Enhanced the outdoor WiFi signal strength",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75932453116013,
          lng: -105.01244836237774,
        },
      },
      {
        id: "lght4",
        title: "Light Interactive Workshop",
        subTitle: "The art of smart lights programming",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75986730174264,
          lng: -105.00059403615393,
        },
      },
      {
        id: "lght5",
        title: "Smart Lights Exhibitiont",
        subTitle: "Display of creativity and technology",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75181100420289,
          lng: -105.01129637456289,
        },
      },
      {
        id: "lght6",
        title: "WiFi Movie Marathon",
        subTitle: "Outdoor movie marathon with WiFi streaming access",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75515362500666,
          lng: -104.99609756758628,
        },
      },
      {
        id: "lght7",
        title: "Light Sculpture Showcase",
        subTitle:
          "The blend of creativity and technology in this stunning showcase",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.749147447458455,
          lng: -105.00751795284174,
        },
      },
      {
        id: "lght8",
        title: "Interactive Light Installation",
        subTitle: "Engage with cutting-edge interactive light installations",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75181100420289,
          lng: -105.00847214637164,
        },
      },
      {
        id: "lght10",
        title: "Light Technology Seminar",
        subTitle: "Discover how innovation is shaping the future of lighting",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.755314112781264,
          lng: -105.0013163832604,
        },
      },
      {
        id: "lght11",
        title: "Smart Lights Power Outage",
        subTitle: "Outdoor smart lights are temporarily unavailable",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.755724996944544,
          lng: -105.0073944803513,
        },
      },
      {
        id: "lght12",
        title: "Lights Connectivity Issue",
        subTitle: "Causing disruptions in lighting patterns",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.754096574426356,
          lng: -104.99524286694944,
        },
      },
      {
        id: "lght13",
        title: "Lights Firmware Update",
        subTitle: "Introduce new features and enhance performance",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.76323809694557,
          lng: -105.00263788550286,
        },
      },
      {
        id: "lght14",
        title: "Malfunctioning Spotlight",
        subTitle: "Spotlight not focusing properly",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.758410381562285,
          lng: -104.99914476116105,
        },
      },
      {
        id: "lght15",
        title: "Uneven Street Lighting",
        subTitle: "Inconsistent brightness along the street",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.758267544591504,
          lng: -104.98829377916307,
        },
      },
      {
        id: "lght16",
        title: "Flashing Neon Sign",
        subTitle: "Neon sign flashing abnormally",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.749982493422706,
          lng: -104.99238147786095,
        },
      },
      {
        id: "lght17",
        title: "Broken Street Lamp",
        subTitle: "Non-functional street lamp",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.7519538545636,
          lng: -105.00639113612544,
        },
      },
      {
        id: "lght18",
        title: "Flickering Lights",
        subTitle: "Lights intermittently turning on and off",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.755724996944544,
          lng: -105.0059452053584,
        },
      },
      {
        id: "lght19",
        title: "Dimmed Lights",
        subTitle: "Reduced brightness in specific areas",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75263953217147,
          lng: -104.99134097273785,
        },
      },
      {
        id: "lght20",
        title: "Lights Connectivity Issue",
        subTitle: "Causing disruptions in lighting patterns",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.7519824246002,
          lng: -105.00928968611122,
        },
      },
      {
        id: "lght91",
        title: "Smart Lights Power Outage",
        subTitle: "Outdoor smart lights are temporarily unavailable",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.74963757446337,
          lng: -105.0282019436024,
        },
      },
      {
        id: "lght92",
        title: "Lights Connectivity Issue",
        subTitle: "Causing disruptions in lighting patterns",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.721761171764804,
          lng: -105.0139690453071,
        },
      },
      {
        id: "lght93",
        title: "Lights Firmware Update",
        subTitle: "Introduce new features and enhance performance",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.72278858360459,
          lng: -105.02156913649932,
        },
      },
      {
        id: "lght21",
        title: "Outdoor Lighting Malfunction",
        subTitle: "Maintenance team notified",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75809613983553,
          lng: -104.99754684257915,
        },
      },
      {
        id: "lght22",
        title: "Floodlight Maintenance",
        subTitle: "Checking and repairing floodlights",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.753039507624166,
          lng: -104.9947226143879,
        },
      },
      {
        id: "lght23",
        title: "Lighting Fixture Replacement",
        subTitle: "Replacing faulty fixtures in the building",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75458224832903,
          lng: -105.00449593036554,
        },
      },
      {
        id: "lght24",
        title: "Maintenance of Landscape Lights",
        subTitle: "Inspecting and cleaning landscape lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75432512727771,
          lng: -105.00505334382431,
        },
      },
      {
        id: "lght25",
        title: "Lighting System Upgrade",
        subTitle: "Upgrading to energy-efficient LED lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75677237845138,
          lng: -104.99989373019561,
        },
      },
      {
        id: "lght26",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75978160140874,
          lng: -104.99776980796267,
        },
      },
      {
        id: "lght28",
        title: "Street Light Replacement",
        subTitle: "Old street lights being replaced",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75838685085751,
          lng: -105.00005180275836,
        },
      },
      {
        id: "lght30",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75722374013964,
          lng: -105.00077442018811,
        },
      },
    ],
  },
};

export default lightingData;
