const lightingData = {
  infoData: {},
  analytics: {},
  notifications: {
    lighting: [
      {
        id: "lght1",
        title: "WiFi Network Upgraded",
        subTitle: "Provide faster and more reliable connectivity",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012339057804061,
          lng: -79.47665814208264,
        },
      },
      {
        id: "lght2",
        title: "WiFi Password Reset",
        subTitle: "Outdoor WiFi network has been reset",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01253100827048,
          lng: -79.47658000143186,
        },
      },
      {
        id: "lght3",
        title: "WiFi Signal Boost",
        subTitle: "Enhanced the outdoor WiFi signal strength",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012471306148246,
          lng: -79.47645784174911,
        },
      },
      {
        id: "lght4",
        title: "Light Interactive Workshop",
        subTitle: "The art of smart lights programming",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012808532307957,
          lng: -79.4764119968662,
        },
      },
      {
        id: "lght5",
        title: "Smart Lights Exhibitiont",
        subTitle: "Display of creativity and technology",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013118726033703,
          lng: -79.47612871661019,
        },
      },
      {
        id: "lght6",
        title: "WiFi Movie Marathon",
        subTitle: "Outdoor movie marathon with WiFi streaming access",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013611386108172,
          lng: -79.47570927025225,
        },
      },
      {
        id: "lght7",
        title: "Light Sculpture Showcase",
        subTitle:
          "The blend of creativity and technology in this stunning showcase",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013444462951556,
          lng: -79.47549236244147,
        },
      },
      {
        id: "lght8",
        title: "Interactive Light Installation",
        subTitle: "Engage with cutting-edge interactive light installations",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013646527815519,
          lng: -79.47572637654648,
        },
      },
      {
        id: "lght10",
        title: "Light Technology Seminar",
        subTitle: "Discover how innovation is shaping the future of lighting",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013778984994607,
          lng: -79.47578248518732,
        },
      },
      {
        id: "lght11",
        title: "Smart Lights Power Outage",
        subTitle: "Outdoor smart lights are temporarily unavailable",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013515422202774,
          lng: -79.47554026006107,
        },
      },
      {
        id: "lght12",
        title: "High Electricity Consumption",
        subTitle: "Light Pole-1",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012950031312087,
          lng: -79.47579712394808,
        },
      },
      {
        id: "lght13",
        title: "Hazardous AQI",
        subTitle: "AQI-200, Light Pole-3",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012748759453942,
          lng: -79.47590201481266,
        },
      },
      {
        id: "lght14",
        title: "High Temperature",
        subTitle: "Temp 104 °F",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012736919929392,
          lng: -79.47611779030552,
        },
      },
      {
        id: "lght15",
        title: "Weak Signal Strength",
        subTitle: "Wifi#23, Light Pole-2",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013222340118126,
          lng: -79.47606084955046,
        },
      },
      {
        id: "lght16",
        title: "High CO2 Level",
        subTitle: "CO2 Level-1501,Light Pole-2",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012846435516755,
          lng: -79.47587204599422,
        },
      },
      {
        id: "lght17",
        title: "Low Bandwidth",
        subTitle: "Wifi#23,Light Pole-3",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012257418858626,
          lng: -79.47595595868589,
        },
      },
      {
        id: "lght18",
        title: "Low Humidity",
        subTitle: "Humidity-20%",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012810916951514,
          lng: -79.47588703040344,
        },
      },
      {
        id: "lght19",
        title: "High Electricity Consumption",
        subTitle: "Light Pole-6",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012118304208366,
          lng: -79.47606384643593,
        },
      },
      {
        id: "lght20",
        title: "Weak Signal Strength",
        subTitle: "Wifi#13, Light Pole-8",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.011869673677204,
          lng: -79.47630959074725,
        },
      },
      {
        id: "lght91",
        title: "High CO2 Level",
        subTitle: "CO2 Level-101,Light Pole-8",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01215678272765,
          lng: -79.4758480709431,
        },
      },
      {
        id: "lght92",
        title: "High Temperature",
        subTitle: "Temp 104 °F",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013018108509902,
          lng: -79.47580012083357,
        },
      },
      {
        id: "lght93",
        title: "Hazardous AQI",
        subTitle: "AQI-300, Light Pole-1",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012390613641395,
          lng: -79.47658230699516,
        },
      },
      {
        id: "lght21",
        title: "Outdoor Lighting Malfunction",
        subTitle: "Maintenance team notified",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012014708174505,
          lng: -79.47630359698356,
        },
      },
      {
        id: "lght22",
        title: "Floodlight Maintenance",
        subTitle: "Checking and repairing floodlights",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012032467496711,
          lng: -79.47597693686244,
        },
      },
      {
        id: "lght23",
        title: "Lighting Fixture Replacement",
        subTitle: "Replacing faulty fixtures in the building",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012032467496711,
          lng: -79.47610280589993,
        },
      },
      {
        id: "lght24",
        title: "Maintenance of Landscape Lights",
        subTitle: "Inspecting and cleaning landscape lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01220710078516,
          lng: -79.47654334753116,
        },
      },
      {
        id: "lght25",
        title: "Lighting System Upgrade",
        subTitle: "Upgrading to energy-efficient LED lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.011837114904507,
          lng: -79.47603687449934,
        },
      },
      {
        id: "lght26",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012651083341776,
          lng: -79.47594996492583,
        },
      },
      {
        id: "lght28",
        title: "Street Light Replacement",
        subTitle: "Old street lights being replaced",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012026547722744,
          lng: -79.47632457515647,
        },
      },
      {
        id: "lght30",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012008788400246,
          lng: -79.47626164063773,
        },
      },
    ],
  },
};

export default lightingData;
