const lightingData = {
  infoData: {},
  analytics: {},
  notifications: {
    lighting: [
      {
        id: "lght1",
        title: "WiFi Network Upgraded",
        subTitle: "Provide faster and more reliable connectivity",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.753160323749114,
          lng: -105.01170566355108,
        },
      },
      {
        id: "lght2",
        title: "WiFi Password Reset",
        subTitle: "Outdoor WiFi network has been reset",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75461968970569,
          lng: -105.00328099939746,
        },
      },
      {
        id: "lght3",
        title: "WiFi Signal Boost",
        subTitle: "Enhanced the outdoor WiFi signal strength",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75055380818962,
          lng: -105.00000034678636,
        },
      },
      {
        id: "lght4",
        title: "Light Interactive Workshop",
        subTitle: "The art of smart lights programming",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75781397788408,
          lng: -104.9972290784235,
        },
      },
      {
        id: "lght5",
        title: "Smart Lights Exhibitiont",
        subTitle: "Display of creativity and technology",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75353297677643,
          lng: -105.00327870264529,
        },
      },
      {
        id: "lght6",
        title: "WiFi Movie Marathon",
        subTitle: "Outdoor movie marathon with WiFi streaming access",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75734526008877,
          lng: -105.00014212993709,
        },
      },
      {
        id: "lght7",
        title: "Light Sculpture Showcase",
        subTitle:
          "The blend of creativity and technology in this stunning showcase",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.749147447458455,
          lng: -105.00751795284174,
        },
      },
      {
        id: "lght8",
        title: "Interactive Light Installation",
        subTitle: "Engage with cutting-edge interactive light installations",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.754428722132545,
          lng: -105.00332616298682,
        },
      },
      {
        id: "lght9",
        title: "Laser Light Show",
        subTitle: "Captivating laser light show synchronized with music",
        area: "OutDoor",
        entity: " ",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.753650251934815,
          lng: -105.01000630268352,
        },
      },
      {
        id: "lght10",
        title: "Light Technology Seminar",
        subTitle: "Discover how innovation is shaping the future of lighting",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "event",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.755314112781264,
          lng: -105.0013163832604,
        },
      },
      {
        id: "lght11",
        title: "Smart Lights Power Outage",
        subTitle: "Outdoor smart lights are temporarily unavailable",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75569604248862,
          lng: -105.00192609171674,
        },
      },
      {
        id: "lght12",
        title: "Lights Connectivity Issue",
        subTitle: "Causing disruptions in lighting patterns",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.756824458797134,
          lng: -105.00113572890297,
        },
      },
      {
        id: "lght13",
        title: "Lights Firmware Update",
        subTitle: "Introduce new features and enhance performance",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75706749988997,
          lng: -104.99973565763285,
        },
      },
      {
        id: "lght14",
        title: "Malfunctioning Spotlight",
        subTitle: "Spotlight not focusing properly",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75428983629226,
          lng: -105.000571184036,
        },
      },
      {
        id: "lght15",
        title: "Uneven Street Lighting",
        subTitle: "Inconsistent brightness along the street",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.757206380129404,
          lng: -104.99978082122222,
        },
      },
      {
        id: "lght16",
        title: "Flashing Neon Sign",
        subTitle: "Neon sign flashing abnormally",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.756234212572515,
          lng: -105.00118089249233,
        },
      },
      {
        id: "lght17",
        title: "Broken Street Lamp",
        subTitle: "Non-functional street lamp",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.7517203977345,
          lng: -105.00170027376996,
        },
      },
      {
        id: "lght18",
        title: "Flickering Lights",
        subTitle: "Lights intermittently turning on and off",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75569604248862,
          lng: -105.00192609171674,
        },
      },
      {
        id: "lght19",
        title: "Dimmed Lights",
        subTitle: "Reduced brightness in specific areas",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.756824458797134,
          lng: -105.00113572890297,
        },
      },
      {
        id: "lght20",
        title: "Lights Connectivity Issue",
        subTitle: "Causing disruptions in lighting patterns",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.757362620063994,
          lng: -104.99867431328295,
        },
      },

      {
        id: "lght21",
        title: "Outdoor Lighting Malfunction",
        subTitle: "Maintenance team notified",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.757327900109146,
          lng: -105.00070667480405,
        },
      },
      {
        id: "lght22",
        title: "Floodlight Maintenance",
        subTitle: "Checking and repairing floodlights",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75838685085751,
          lng: -105.00005180275836,
        },
      },
      {
        id: "lght23",
        title: "Lighting Fixture Replacement",
        subTitle: "Replacing faulty fixtures in the building",
        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75788341728617,
          lng: -105.00061634762534,
        },
      },
      {
        id: "lght24",
        title: "Maintenance of Landscape Lights",
        subTitle: "Inspecting and cleaning landscape lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75564396128959,
          lng: -105.00192609171674,
        },
      },
      {
        id: "lght25",
        title: "Lighting System Upgrade",
        subTitle: "Upgrading to energy-efficient LED lights",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.756581416846664,
          lng: -104.9982000955947,
        },
      },
      {
        id: "lght26",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.757605659257756,
          lng: -104.99953242148075,
        },
      },
      {
        id: "lght27",
        title: "Spotlight Realignment",
        subTitle: "Adjusting spotlights for better coverage",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.757327900109146,
          lng: -105.00070667480405,
        },
      },
      {
        id: "lght28",
        title: "Street Light Replacement",
        subTitle: "Old street lights being replaced",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75838685085751,
          lng: -105.00005180275836,
        },
      },
      {
        id: "lght29",
        title: "Dimmed Pathway Lights",
        subTitle: "Low brightness along the pathway",

        area: "OutDoor",
        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75765773897343,
          lng: -105.0017454373593,
        },
      },
      {
        id: "lght30",
        title: "New Lighting Installation",
        subTitle: "Installing additional lights in the park",

        area: "OutDoor",

        entity: "",
        venue: "Location",
        category: "lighting",
        notificationCategory: "oprAlert",
        timeStamp: "09:41 AM",
        location: {
          lat: 39.75722374013964,
          lng: -105.00077442018811,
        },
      },
    ],
  },
};

export default lightingData;
