const securityData = {
  infoData: {
    day: {
      fireDetection: 5,
      tamperingAlarm: 10,
      unauthorizedAccess: 2,
      tailGating: 4,
      cameraOcclusion: 11,
      issuesResolved: 30,
    },
    week: {
      fireDetection: 15,
      tamperingAlarm: 20,
      unauthorizedAccess: 14,
      tailGating: 15,
      cameraOcclusion: 17,
      issuesResolved: 50,
    },
    month: {
      fireDetection: 25,
      tamperingAlarm: 30,
      unauthorizedAccess: 25,
      tailGating: 28,
      cameraOcclusion: 20,
      issuesResolved: 70,
    },
    year: {
      fireDetection: 50,
      tamperingAlarm: 75,
      unauthorizedAccess: 78,
      tailGating: 66,
      cameraOcclusion: 33,
      issuesResolved: 80,
    },
  },
  analytics: {},
  notifications: {
    security: [
      {
        id: "sec1",
        title: "Maintenance Completed",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013191247669306,
          lng: -79.47640581615131,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec2",
        title: "Maintenance In-progress",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013098293457437,
          lng: -79.47575453126504,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec3",
        title: "Maintenance Completed",
        area: "Entrance A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013302792691961,
          lng: -79.47622511283026,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec4",
        title: "Scheduled Maintenance",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013139193313599,
          lng: -79.47599923367895,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec5",
        title: "Maintenance Completed",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013667172859288,
          lng: -79.47586370618818,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec6",
        title: "Maintenance In-progress",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013317665359049,
          lng: -79.47609711464452,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec7",
        title: "Maintenance Completed",
        area: "Entrance B",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Events",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012793403474594,
          lng: -79.47613476116975,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec11",
        title: "Unauthorized Access",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012852894223169,
          lng: -79.47643593337148,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec12",
        title: "Tempering Alarm",
        area: "Zone 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012971875690903,
          lng: -79.47633805240592,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec13",
        title: "Intrusion Detected",
        area: "Zone A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01312060247046,
          lng: -79.47574700195999,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec14",
        title: "Tailgating",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013715508976324,
          lng: -79.47574700195999,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec15",
        title: "Camera Occlusion",
        area: "Zone B",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013083420781317,
          lng: -79.47626275935548,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec16",
        title: "Camera Offline",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012696730987289,
          lng: -79.47617993700001,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec17",
        title: "Camera Not Operational",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012529413159651,
          lng: -79.47620252491514,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec18",
        title: "Unauthorized Access",
        area: "Zone A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012690121020169,
          lng: -79.47620080380786,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec19",
        title: "Low Humidity",
        area: "Zone 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013288082329495,
          lng: -79.47612007891705,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec20",
        title: "Fire Detection",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012349061163416,
          lng: -79.47625462040173,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec82",
        title: "Fire Detection",
        area: "Zone 5",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012650256897695,
          lng: -79.47615147193014,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec83",
        title: "Intrusion Detected",
        area: "Zone H",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Incident",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012791995979876,
          lng: -79.47596311385159,
        },
        equipment: "Cam - 3",
      },
      {
        id: "sec21",
        title: "Firewall Alert",
        area: "Zone A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012902729599116,
          lng: -79.47614698721398,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec22",
        title: "Maintenance Due",
        area: "Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013221642232894,
          lng: -79.47610214005243,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec23",
        title: "Low Battery Level",
        area: "Zone A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01323050091315,
          lng: -79.47614698721398,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec24",
        title: "Access Control System Offline",
        area: "Zone B ",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.013199495531312,
          lng: -79.47587341952847,
        },
        equipment: "Cam - 4",
      },
      {
        id: "sec25",
        title: "Maintenance Due",
        area: "Lobby Area 1",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012300338300445,
          lng: -79.47644746319644,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec26",
        title: " Alarm Triggered ",
        area: " Security Team Investigating in Lobby Area 2",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01288501222232,
          lng: -79.47585996538,
        },
        equipment: "Cam - 2",
      },
      {
        id: "sec27",
        title: "Access Control System Offline",
        area: "Zone A",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.012823001396676,
          lng: -79.47613353306551,
        },
        equipment: "Cam - 1",
      },
      {
        id: "sec30",
        title: "Maintenance Due",
        area: "Lobby Area 1 ",
        entity: "",
        venue: "Location",
        category: "security",
        notificationType: "Alerts",
        timeStamp: "09:41 AM",
        location: {
          lat: 9.01272112644572,
          lng: -79.47633086057638,
        },
        equipment: "Cam - 4",
      },
    ],
  },
};
export default securityData;
