export default {
  helloInfinite: "Hello Infinite",
  changeTheme: "Change Theme",
  changeLang: "Change Language",
  title: "Hello Infinite English",
  profile: "Profile",
  hello: "Hello",
  virtualTrackerIoT: "Virtual Tracker IoT",
  loginDescription: `Industry to explore different use cases for tracking assets,
    materials and inventory.`,
  welcomBack: "Welcome back",
  signInTitle: "Sign in to Virtual Tracker IoT",
  yourEmail: "Username",
  passwordTItle: "Password",
  loginNowButton: "Login now",
  copyRightTitle: "Have any issue?",
  contactSupport: "Contact Support.",
  settings: "Settings",
  serialNo: "Serial No",
  batteryText: "Battery",
  temperatureText: "Temperature",
  humidityText: "Humidity",
  geofenceText: "Geofence",
  tracker: "Trackers",
  configuration: "Configuration",
  type: "Type",
  model: "Model",
  oprTemp: "Opr.Temp",
  sensitivity: "Sensitivity",
  sensor: "Sensor",
  batteryType: "Battery Type",
  lastUpdated: "Last Updated",
  geoLocationLastUpdate: "Geo Location Last Update",
  history: "History",
  noDataAvailable: "No Data Available",
  noOfTags: "No. of Tags",
  eventsText: "Events",
  incidentText: "Incident",
  opsAlertText: "Ops. Alert",
  trackingText: "Tracking",
  notificationText: "Notifications",
  all: "All",
  rtls: "RTLS",
  ble: "BLE",
  withInGeofence: "With in Geofence",
  outsideGeofence: "Outside of Geofence",
  viewDetails: "View Details",
  noResultFound: "No Result Found",
  contactAdmin: "Contact Admin",
  operationalTemperature: "Operational Temperature",
  batteryLevel: "Battery Level",
  status: "Status",
  minimum: "Minimum",
  maximum: "Maximum",
  raiseIncident: "Raise Incident",
  noGeofence: "No Geofence",
  addGroupTracker: "ADD GROUP TRACKER",
  groupId: "GROUP ID",
  groupName: "Group Name",
  groupType: "Group Type",
  selectGroupType: "Select group type",
  noTagSelected: "No Tag Selected",
  save: "Save",
  dashboard: "Dashboard",
  trackerSidebar: "Tracker",
  analytics: "Analytics",
  settingsSidebar: "Settings",
  poweredBy: "Powerdby",
  profileSidebar: "Profile",
  logout: "Logout",
  searchText: "Search",
  enabledGeofenceText: "Enabled Geofence",
  disabledGeofenceText: "Disabled Geofence",
  geofenceTypeText: "Geofence Type",
  centerLocationText: "Center Location",
  lattitudeText: "Latitude",
  longitudeText: "Longitude",
  geofenceRadiusText: "Geofence Radius",
  outsideRaiseIncidentText: "Outside of Geofence Raise Incident",
  backRaiseEventText: "Back to Geofence Raise Event",
  restorePreviousText: "Restore Previous",
  trackerText: "Tracker",
  trackerTypeText: "Tracker Type",
  selectTrackerType: "Select tracker type",
  errorMsgTrackerType: "Please select tracker type",
  trackerIDText: "Tracker ID",
  trackerNameText: "Tracker Name",
  errorMsgTrackerName: "Please enter tracker name",
  makeText: "Make",
  enterMake: "Enter Make",
  modelText: "Model",
  enterModel: "Enter Model",
  groupTypeText: "Group Type",
  attributesText: "Attributes",
  sensitivityText: "Sensitivity",
  rangeText: "Range",
  enterRange: "Enter Range",
  batteryTypeText: "Battery Type",
  enterBatteryType: "Enter Battery Type",
  errorMsgGroupType: "Please select group type",
  batteryLife: "Battery Life",
  selectBatteryLife: "Select Battery Life",
  operationalTemperatureText: "Operational Temperature",
  addNewConfiguration: "Add New Configuration",
  selectTypeText: "Select Type",
  pleaseSelectType: "Please select type",
  pleaseEnterLatitude: "Please enter latitude",
  pleaseEnterLongitude: "Please enter longitude",
  enterGeofenceRadius: "Enter Geofence Radius",
  errorMsgEnterRadius: "Please enter radius",
  previousText: "Previous",
  saveText: "Save",
  nextText: "Next",
  createTrackerText: "Create Tracker",
  addTrackerText: "Add Tracker",
  stepText: "STEP",
  nameText: "Name",
  iDText: "ID",
  locationText: "Location",
  stateText: "State",
  actionsText: "Actions",
  assignedTrackers: "Assigned Trackers",
  groupText: "Groups",
  allTrackerText: "All Trackers",
  allGroupsText: "All Groups",
  addGroupText: "Add Group",
  onlineTracker: "Online Trackers",
  offlineTracker: "Offline Trackers",
  normalBattery: "Normal Battery",
  lowBattery: "Low Battery",
  updateText: "Update",
};
