export default {
  helloInfinite: "Hello Infinite",
  changeTheme: "Change Theme",
  changeLang: "Change Language",
  title: "Hello Infinite English",
  profile: "Profile",
  hello: "Hello",
  virtualTrackerIoT: "Virtual Tracker IoT",
  loginDescription: `Industry to explore different use cases for tracking assets,
    materials and inventory.`,
  welcomBack: "Welcome back",
  signInTitle: "Sign In",
  yourEmail: "Username",
  passwordTItle: "Password",
  loginNowButton: "Login now",
  poweredByText: "Powered by",
  allRightsReservedText: "All Rights Reserved",
  titleText: "Sensyon",
  subTitleText: "Iot Accelerated",
  homeText: "Home",
  gridsViewText: "Grid View",
  birdsViewText: "Birds View",
  settingsText: "Settings",
  notificationText: "Notifications",
  eventText: "Events",
  incidentText: "Incidents",
  oprAlertText: "Opr.Alerts",
};
