export default {
  helloInfinite: "Hola Infinite",
  changeTheme: "Cambia Tema",
  changeLang: "Change Lingua",
  title: "Hello Infinite Italian",
  profile: "Profilo",
  hello: "Hola",
  virtualTrackerIoT: "Virtual Tracker IoT Test",
  loginDescription: `Industria per esplorare diversi casi d'uso per il monitoraggio delle risorse,
    materiali e inventario.`,
  welcomBack: "Bentornato",
  signInTitle: "Accedi a Virtual Tracker IoT",
  yourEmail: "nome utente",
  passwordTItle: `Parola d'ordine`,
  loginNowButton: "Login now",
  copyRightTitle: "Hai qualche problema?",
  contactSupport: "Contatta il supporto.",
  settings: "Impostazioni",
  serialNo: "Numero di serie",
  batteryText: "Batteria",
  temperatureText: "Temperatura",
  humidityText: "Umidità",
  geofenceText: "Geofence",
  tracker: "Localizzatore",
  configuration: "Configurazione",
  type: "Tipo",
  model: "Modello",
  oprTemp: "Opr.Temp",
  sensitivity: "Sensibilità",
  sensor: "Sensore",
  batteryType: "Tipo di batteria",
  lastUpdated: "Ultimo aggiornamento",
  geoLocationLastUpdate: "Geolocalizzazione Ultimo aggiornamento",
  history: "Storia",
  noDataAvailable: "Nessun dato disponibile",
  noOfTags: "Numero. di Tag",
  eventsText: "Eventi",
  incidentText: "Incidente",
  opsAlertText: "Ops. Mettere in guardia",
  trackingText: "Monitoraggio",
  notificationText: "Notifica",
  all: "Tutto",
  rtls: "RTLS",
  ble: "BLE",
  withInGeofence: "Con in Geofence",
  outsideGeofence: "Al di fuori di Geofence",
  viewDetails: "Visualizza Dettagli",
  noResultFound: "Nessun Risultato Trovato",
  contactAdmin: "Contatta l'Amministratore",
  operationalTemperature: "Temperatura operativa",
  batteryLevel: "Livello della batteria",
  status: "Stato",
  minimum: "Minimo",
  maximum: "Massimo",
  raiseIncident: "Aumenta incidente",
  noGeofence: "Nessun Georecinto",
  addGroupTracker: "AGGIUNGI UN RILEVATORE DI GRUPPO",
  groupId: "ID GRUPPO",
  groupName: "Nome del gruppo",
  groupType: "Tipo di gruppo",
  selectGroupType: "Seleziona il tipo di gruppo",
  noTagSelected: "Nessun tag selezionato",
  save: "Salva",
  dashboard: "Pannello di controllo",
  trackerSidebar: "Localizzatore",
  analytics: "analitica",
  settingsSidebar: "Ajustes",
  poweredBy: "Offerto da",
  profileSidebar: "Profilo",
  logout: "Disconnettersi",
  searchText: "Ricerca",
  enabledGeofenceText: "Geofence Abilitato",
  disabledGeofenceText: "Geofence Disattivato",
  geofenceTypeText: "Geofence Tipa",
  centerLocationText: "Posizione Centrale",
  lattitudeText: "Latitudine",
  longitudeText: "Longitudine",
  geofenceRadiusText: "Geofence Raggio",
  outsideRaiseIncidentText: "Al di fuori di Geofence Aumenta incidente",
  backRaiseEventText: "Torniamo a Geofence Aumenta Evento",
  restorePreviousText: "Ristabilire Precedente",

  trackerText: "Localizzatore",
  trackerTypeText: "Tipo di localizzatore",
  selectTrackerType: "Seleziona il tipo di localizzatore",
  errorMsgTrackerType: "Per favore Seleziona il tipo di localizzatore",
  trackerIDText: "Identificativo del localizzatore",
  trackerNameText: "Nome del localizzatore",
  errorMsgTrackerName: "Inserisci il nome del localizzatore",
  makeText: "Fare",
  enterMake: "Accedere Fare",
  modelText: "Modello",
  enterModel: "Accedere Modello",
  groupTypeText: "Tipo di Gruppo",
  attributesText: "Attributi",
  sensitivityText: "Sensibilità",
  rangeText: "Allineare",
  enterRange: "Accedere Allineare",
  batteryTypeText: "Tipo di batteria",
  enterBatteryType: "Accedere Tipo di batteria",
  errorMsgGroupType: "Per favore Selezionare tipo di gruppo",
  batteryLife: "Durata della batteria",
  selectBatteryLife: "Selezionare Durata della batteria",
  operationalTemperatureText: "Temperatura Operativa",
  addNewConfiguration: "Aggiungi nuova configurazione",
  selectTypeText: "Selezionare Type",
  pleaseSelectType: "Per favore Selezionare type",
  pleaseEnterLatitude: "Per favore accedere Latitudine",
  pleaseEnterLongitude: "Per favore accedere Longitudine",
  enterGeofenceRadius: "Accedere Geofence Raggio",
  errorMsgEnterRadius: "Per favore accedere Raggio",
  previousText: "Precedente",
  saveText: "Salva",
  nextText: "Prossima",
  createTrackerText: "Crea Localizzatore",
  addTrackerText: "Aggiungi Localizzatore",
  stepText: "PASSO",
  nameText: "Nome",
  iDText: "ID",
  locationText: "Posizione",
  stateText: "Stato",
  actionsText: "Azione",
  assignedTrackers: "Assegnato Localizzatore",
  groupText: "Gruppi",
  allTrackerText: "Tutto Localizzatore",
  allGroupsText: "Tutto Gruppi",
  addGroupText: "Add Gruppi",
  onlineTracker: "In linea Localizzatore",
  offlineTracker: "Disconnesso Localizzatore",
  normalBattery: "Normale Batteria",
  lowBattery: "Basso Batteria",
  updateText: "Aggiornamento",
};
