export default {
  helloInfinite: "Hola Infinite",
  changeTheme: "Cambia Tema",
  changeLang: "Change Lingua",
  title: "Hello Infinite Italian",
  profile: "Profilo",
  hello: "Hola",
  virtualTrackerIoT: "Virtual Tracker IoT Test",
  loginDescription: `Industria per esplorare diversi casi d'uso per il monitoraggio delle risorse,
    materiali e inventario.`,
  welcomBack: "Bentornato",
  signInTitle: "Accedi a",
  yourEmail: "nome utente",
  passwordTItle: `Parola d'ordine`,
  loginNowButton: "Login now",
  poweredByText: "Offerto da",
  allRightsReservedText: "Tutti i diritti riservati",
  titleText: "Sension",
  subTitleText: "IoT accelerato",
  homeText: "Casa",
  gridsViewText: "Vista a griglia",
  birdsViewText: "Vista degli uccelli",
  settingsText: "Impostazioni",
  notificationText: "Notifica",
  eventText: "Eventi",
  incidentText: "Incidenti",
  oprAlertText: "Opr.Avvisi",
  searchText: "Ricerca",
  noResultFound: "Nessun Risultato Trovato",
  dashboard: {
    parking: "Parcheggio",
    energyManagement: "Gestione dell'energia",
    security: "Sicurezza",
    lighting: "Illuminazione",
    fleetManagement: "Gestione della flotta",
    assetsTracking: "Monitoraggio delle risorse",
    parkingNoteLabel: "Ore di guida risparmiate",
    energyNoteLabel: "Energia consumata",
    securityNoteLabel: "Violazioni della sicurezza evitate",
    electricityNoteLabel: "Elettricità consumata",
    tripsNoteLabel: "Viaggi completati",
    assetsNoteLabel: "Località cambiata",
    available: "disponibile",
    occupied: "occupata",
    consumed: "consumata",
    savings: "risparmio",
    cameras: "fotografiche",
    alerts: "avvisi",
    electricity: "elettricità",
    data: "dati",
    fleet: "flotta",
    trips: "viaggi",
    assets: "risorse",
    runningUnits : "CORSA UNITÀ",
    alertsText: "AVVISI",
    smartLights : "LUCI INTELLIGENTI",
    violations : "VIOLAZIONI"
  },
  gridView: {
    today: "Oggi",
    avg: "Med",
    parkingHours: "Parcheggio ore.",
    rotation: "Rotazione",
    index: "Indice",
    carbon: "Carbonio",
    emission: "Emissione",
    occupancy: "Occupazione",
    electricityConsumption: "Consumo elettrico",
    waterConsumption: "Consumo d'acqua",
    energy: "Energia",
    consumption: "Consumo",
    saved: "Salvato",
    cost: "Costo",
    securityAlerts: "Avvisi di sicurezza",
    fire: "Fuoco",
    detection: "Rilevamento",
    tempering: "Tempra",
    alarm: "Allarme",
    unauthorised: "Non autorizzato",
    access: "Accesso",
    wifiUsers: "Utenti Wi-Fi",
    avgDimmingLevel: "Medio, livello di attenuazione",
    consumed: "CONSUMATO",
    aqi: "AQI",
    co2: "CO2",
    voc: "VOC",
    level: "Livello",
    pm25: "PM2.5",
    overspeeding: "Velocità eccessiva",
    harshBreaking: "Rottura dura",
    vehicles: "Veicoli",
    trips: "Viaggi",
    incidents: "Incidenti",
    total: "Totale",
    distance: "Distanza",
    idling: "Inattivo",
    hours: "Ore",
    assets: "Risorse",
    tracked: "Tracciata",
    location: "Posizione",
    changes: "I cambiamenti",
    outOf: "Fuori da",
    geofence: "Geofence",
  },
  parking: {
    parkingViolation: "Infrazione divieto sosta",
    all: "Tutto"
  },
  security: {
    security: "Sicurezza",
    issuesResolved: "Problemi risolti",
    intrusion: "Intrusione",
    fireDetection: "Rilevazione incendi",
    temperingAlarm: "Allarme tempra",
    unauthorisedAccess: "Accesso non autorizzato",
    tailgating: "Tailgating"
  },
  lighting: {
    airQualityIndex: "Indice di qualità dell'aria"
  },
  fleetManagement: {
    safetyScore: "Punteggio di sicurezza",
    trips: "Viaggi",
    distanceTravelled: "Distanza percorsa",
    driveHrs: "Guidare ore",
    idleHrs: "Ore di inattività",
    harshAcceleration: "Brusca accelerazione",
    tripDetail: "Dettaglio del viaggio",
    vehicleDetail: "Dettagli del veicolo",
    driverDetail: "Dettaglio conducente",
    stops: "Fermate",
    tripCompletion: "Completamento del viaggio",
    distanceCovered: "Distanza ricoperta",
    totalTime: "Tempo totale",
    violations: "Violazioni",
    cornering: "In curva",
    distraction: "Distrazione",
    fatigueLevel: "Livello di fatica",
    speed: "Velocità",
    licensePlateNumber: "Numero di targa",
    driverName: "Nome del conducente",
    vehicleType: "tipo di veicolo",
    drivingLicense: "Patente di guida",
    totalTrips: "Viaggi totali",
    driven: "Guidata",
    status: "Stato",
    feulConsumed: "Carburante consumato"
  },
  assetsTracking: {
    activeTrackers: "Tracker attivi",
    activeTracker: "Localizzatore attivo",
    inactiveTracker: "Tracker attivo",
    incidents: "Incidenti",
    assetsTracked: "Risorse monitorate",
    product: "Prodotto",
    trackerId: "Identificativo del localizzatore",
    assetsType: "Tipo di attività",
    assetsId: "id",
    section: "Sezione",
    storageLocation: "Posizione di archiviazione",
    trackerStatus: "Stato del localizzatore",
    geofence: "Geofence",
    battery: "Batteria",
    temperature: "Temperatura",
    humidity: "Umidità",
    enabledGeofence: "Geofence abilitato",
    geofenceType: "Tipo di recinto virtuale",
    geofenceName: "Nome recinto geografico",
    notify: "Notificare",
    outsideGeofence: "Al di fuori di Geofence",
    backToGeofence: "Torniamo a Geofence",
    assetDetails: "DETTAGLI PATRIMONIO",
    GEOFENCE: "GEOFENCE",
    centerLocation: "Posizione centrale",
    circle: "Cerchio",
    polygon: "Poligono",
  }
};
