export default {
  changeTheme: "Change Theme",
  changeLang: "Change Language",
  title: "Hello Infinite English",
  profile: "Perfil",
  hello: "Hello",
  virtualTrackerIoT: "Virtual Tracker IoT",
  loginDescription: `Industry to explore different use cases for tracking assets,
      materials and inventory.`,
  welcomBack: "Welcome back",
  signInTitle: "Sign in to Virtual Tracker IoT",
  yourEmail: "Your Email",
  passwordTItle: "Password",
  loginNowButton: "Login now",
  poweredByText: "Powered by",
  allRightsReservedText: "All Rights Reserved",
  titleText: "Sensyon",
  subTitleText: "Iot Accelerated",
};
