export default {
  footerText: `impulsado por Liberty Latinoamérica | Sensión | © 2023 | Todos los derechos
  Reservado`,
  changeTheme: "Change Theme",
  changeLang: "Change Language",
  title: "Hello Infinite English",
  profile: "Perfil",
  hello: "Hello",
  virtualTrackerIoT: "Virtual Tracker IoT",
  loginDescription: `Industry to explore different use cases for tracking assets,
      materials and inventory.`,
  welcomBack: "Welcome back",
  signInTitle: "Iniciar sesión",
  yourEmail: "Your Email",
  passwordTItle: "Password",
  loginNowButton: "Inicia sesión ahora",
  poweredByText: "Powered by",
  allRightsReservedText: "All Rights Reserved",
  titleText: "Sensyon",
  subTitleText: "Iot Accelerated",
  homeText: "Hogar",
  gridsViewText: "Vista en cuadrícula",
  birdsViewText: "Vista de pájaros",
  settingsText: "Ajustes",
  notificationText: "Notificaciones",
  eventText: "Eventos",
  incidentText: "incidentes",
  oprAlertText: "Opr.Alertas",
  noResultFound: "No se han encontrado resultados",
  searchText: "Buscar",
  viewDetails: "Ver detalles",
  takeAction: "Tomar acción",
  dashboardOld: {
    parking: "Parking",
    energyManagement: "Energy Management",
    security: "Security",
    lighting: "Lighting",
    fleetManagement: "Fleet Management",
    assetsTracking: "Assets Tracking",
    parkingNoteLabel: "Drive hours saved",
    energyNoteLabel: "Energy Consumed",
    securityNoteLabel: "Security Breaches Avoided",
    electricityNoteLabel: "Electricity Consumed",
    tripsNoteLabel: "Trips Completed",
    assetsNoteLabel: "Location Changed",
    runningUnits : "CORRER UNIDADES",
    alertsText: "ALERTAS",
    smartLights : "LUCES INTELIGENTES",
    violations : "VIOLACIONES"
  },

  dashboard: {
    parking: "ESTACIONAMIENTO",
    energyManagement: "GESTIÓN DE LA ENERGÍA",
    security: "SEGURIDAD",
    lighting: "ENCENDIENDO",
    fleetManagement: "GESTIÓN DE FLOTAS",
    assetsTracking: "SEGUIMIENTO DE ACTIVOS",
    parkingNoteLabel: "Horas de conducción ahorradas",
    energyNoteLabel: "Energía consumida",
    securityNoteLabel: "Violaciones de seguridad evitadas",
    electricityNoteLabel: "Electricidad consumida",
    tripsNoteLabel: "Viajes completados",
    assetsNoteLabel: "Ubicación cambiada",
    available: "DISPONIBLE",
    occupied: "OCUPADO",
    consumed: "consumado",
    savings: "ahorros",
    cameras: "cámaras",
    alerts: "alertas",
    electricity: "electricidad",
    data: "datos",
    fleet: "flotas",
    trips: "excursiones",
    assets: "activos",
    runningUnits : "UNIDADES OPERATIVAS",
    alertsText: "ALERTAS",
    smartLights : "LUCES INTELIGENTES",
    violations : "VIOLACIONES",
    logout: "Cerrar sesión"
  },

  gridView: {
    today: "Hoy",
    avg: "Prom.",
    parkingHours: "Estacionamiento Hrs.",
    rotation: "Rotación",
    index: "Índice",
    carbon: "Carbón",
    emission: "Emisión",
    occupancy: "Ocupación",
    electricityConsumption: "Consumo de electricidad",
    waterConsumption: "Consumo de agua",
    energy: "Energía",
    consumption: "Consumo",
    saved: "Salvado",
    cost: "Costo",
    securityAlerts: "Alertas de seguridad",
    fire: "Fuego",
    detection: "Detección",
    tempering: "Templado",
    alarm: "Alarma",
    unauthorised: "No autorizado",
    access: "Acceso",
    wifiUsers: "Usuarios Wifi",
    avgDimmingLevel: "Avg, Nivel de atenuación",
    consumed: "CONSUMADO",
    aqi: "AQI",
    co2: "CO2",
    voc: "VOC",
    level: "Nivel",
    pm25: "PM2.5",
    overspeeding: "exceso de velocidad",
    harshBreaking: "Frenado brusco",
    vehicles: "vehículos",
    trips: "Excursiones",
    incidents: "incidentes",
    total: "Total",
    distance: "Distancia",
    idling: "De marcha en vacío",
    hours: "Horas",
    assets: "Assets",
    tracked: "Seguimiento",
    location: "Ubicación",
    changes: "Cambios",
    outOf: "Fuera de",
    geofence: "Geocerca",
  },
  parking: {
    parkingViolation: "Parking Violation",
    all: "All",
  },
  security: {
    security: "Security",
    issuesResolved: "Issues Resolved",
    intrusion: "Intrusion",
    fireDetection: "Fire Detection",
    temperingAlarm: "Tempering Alarm",
    unauthorisedAccess: "Unauthorised Access",
    tailgating: "Tailgating"
  },
  lighting: {
    airQualityIndex: "Índice de calidad del aire"
  },
  fleetManagement: {
    safetyScore: "Safety Score",
    trips: "Trips",
    distanceTravelled: "Distance Travelled",
    driveHrs: "Drive Hrs",
    idleHrs: "Idle Hours",
    harshAcceleration: "Harsh Acceleration",
    tripDetail: "Trip Detail",
    vehicleDetail: "Vehicle Detail",
    driverDetail: "Driver Detail",
    stops: "Stops",
    tripCompletion: "Trip Completion",
    distanceCovered: "Distance Covered",
    totalTime: "Total Time",
    violations: "Vioalations",
    cornering: "Cornering",
    distraction: "Distrazione",
    fatigueLevel: "Fatigue Level",
    speed: "Speed",
    licensePlateNumber: "License Plate Number",
    driverName: "Driver Name",
    vehicleType: "Vehicle Type",
    drivingLicense: "Driving License",
    totalTrips: "Total Trips",
    driven: "Driven",
    status: "Status",
    feulConsumed: "Fuel Consumed",
    drivingScore: "Driving Score",
    covored: "Covered"
  },
  assetsTracking: {
    activeTrackers: "Active Trackers",
    activeTracker: "Active Tracker",
    inactiveTracker: "In-Active Tracker",
    incidents: "Incidents",
    assetsTracked: "Assets Tracked",
    product: "Product",
    trackerId: "Tracker Id",
    assetsType: "Assets Type",
    assetsId: "Assets Id",
    section: "Section",
    storageLocation: "Storage Location",
    trackerStatus: "Tracker Status",
    geofence: "Geofence",
    battery: "Battery",
    temperature: "Temperature",
    humidity: "Humidity",
    enabledGeofence: "Enabled Geofence",
    geofenceType: "Geofence Type",
    geofenceName: "Geofence Name",
    notify: "Notify",
    outsideGeofence: "Outside of Geofence",
    backToGeofence: "Back to Geofence",
    assetDetails: "ASSET DETAILS",
    GEOFENCE: "GEOFENCE",
    centerLocation: "Center Location",
    circle: "Circle",
    polygon: "Polygon",
  }
};
