export default {
  helloInfinite: "Hello Infinite",
  changeTheme: "Change Theme",
  changeLang: "Change Language",
  title: "Hello Infinite English",
  profile: "Perfil",
  hello: "Hello",
  virtualTrackerIoT: "Virtual Tracker IoT",
  loginDescription: `Industry to explore different use cases for tracking assets,
      materials and inventory.`,
  welcomBack: "Welcome back",
  signInTitle: "Sign in to Virtual Tracker IoT",
  yourEmail: "Your Email",
  passwordTItle: "Password",
  loginNowButton: "Login now",
  copyRightTitle: "Have any issue?",
  contactSupport: "Contact Support.",
  settings: "Ajustes",
  serialNo: "Número de serie",
  batteryText: "Batería",
  temperatureText: "Temperatura",
  humidityText: "Humedad",
  geofenceText: "Geocerca",
  tracker: "Rastreador",
  configuration: "Configuración",
  type: "Tipo",
  model: "Modelo",
  oprTemp: "Opr.Temp",
  sensitivity: "Sensibilidad",
  sensor: "Sensor",
  batteryType: "Tipo de Batería",
  lastUpdated: "Última actualización",
  geoLocationLastUpdate: "Ubicación geográfica Última actualización",
  history: "Historia",
  noDataAvailable: "Datos no disponibles",
  noOfTags: "Número de etiquetas",
  eventsText: "Eventos",
  incidentText: "Incidente",
  opsAlertText: "Operaciones Alerta",
  trackingText: "Seguimiento",
  notificationText: "Notificación",
  all: "Toda",
  rtls: "RTLS",
  ble: "BLE",
  withInGeofence: "Con en Geocerca",
  outsideGeofence: "Fuera de la geocerca",
  viewDetails: "Ver detalles",
  noResultFound: "No se han encontrado resultados",
  contactAdmin: "Administrador De Contacto",
  operationalTemperature: "Temperatura operativa",
  batteryLevel: "Nivel de bateria",
  status: "Estado",
  minimum: "Mínimo",
  maximum: "Máximo",
  raiseIncident: "Levantar incidente",
  noGeofence: "Sin Geocerca",
  addGroupTracker: "AÑADIR SEGUIMIENTO DE GRUPO",
  groupId: "DEL GRUPO ID",
  groupName: "Nombre del grupo",
  groupType: "Tipo de grupo",
  selectGroupType: "Seleccionar tipo de grupo",
  noTagSelected: "Ninguna etiqueta seleccionada",
  save: "Ahorrar",
  dashboard: "Panel",
  trackerSidebar: "Rastreador",
  analytics: "analítica",
  settingsSidebar: "Impostazioni",
  poweredBy: "Energizado por",
  profileSidebar: "Perfil",
  logout: "Cerrar sesión",
  searchText: "Buscar",
  enabledGeofenceText: "Activada Geocerca",
  disabledGeofenceText: "Desactivada Geocerca",
  geofenceTypeText: "Geocerca Tipo",
  centerLocationText: "Ubicación Del Centro",
  lattitudeText: "Latitud",
  longitudeText: "Longitud",
  geofenceRadiusText: "Geocerca Radio",
  outsideRaiseIncidentText: "Fuera de la Geocerca Aumentar Incidente",
  backRaiseEventText: "Volver a Geocerca Aumentar Evento",
  restorePreviousText: "Restaurar Previa",
  trackerText: "Rastreador",
  trackerTypeText: "Rastreador Tipo",
  selectTrackerType: "Seleccionar Rastreador Tipo",
  errorMsgTrackerType: "Por favor Seleccionar Rastreador Tipo",
  trackerIDText: "Rastreador ID",
  trackerNameText: "Rastreador Nombre",
  errorMsgTrackerName: "Por favor enter Rastreador Nombre",
  makeText: "Hacer",
  enterMake: "Ingresar Hacer",
  modelText: "Modelo",
  enterModel: "Ingresar Modelo",
  groupTypeText: "Grupo Tipo",
  attributesText: "Atributos",
  sensitivityText: "Sensibilidad",
  rangeText: "Rango",
  enterRange: "Ingresar Rango",
  batteryTypeText: "Batería Tipo",
  enterBatteryType: "Ingresar Batería Tipo",
  errorMsgGroupType: "Por favor Seleccionar Grupo Tipo",
  batteryLife: "Batería Vida",
  selectBatteryLife: "Seleccionar Batería Vida",
  operationalTemperatureText: "Temperatura operativa",
  addNewConfiguration: "Agregar nueva configuración",
  selectTypeText: "Seleccionar Tipo",
  pleaseSelectType: "Por favor Seleccionar Tipo",
  pleaseEnterLatitude: "Por favor Ingresar latitud",
  pleaseEnterLongitude: "Por favor Ingresar Longitud",
  enterGeofenceRadius: "Ingresar Geocerca Radio",
  errorMsgEnterRadius: "Por favor Ingresar Radio",
  previousText: "Previo",
  saveText: "Ahorrar",
  nextText: "Próximo",
  createTrackerText: "Crear Rastreador",
  addTrackerText: "Agregar rastreador",
  stepText: "PASO",
  nameText: "Nombre",
  iDText: "ID",
  locationText: "Ubicación",
  stateText: "Estado",
  actionsText: "Acción",
  assignedTrackers: "Asignado Rastreador",
  groupText: "Grupos",
  allTrackerText: "Todo Rastreador",
  allGroupsText: "Todos los grupos",
  addGroupText: "Agregar grupos",
  onlineTracker: "En línea Rastreador",
  offlineTracker: "Desconectado Rastreador",
  normalBattery: "Normal Batería",
  lowBattery: "Bajo Batería",
  updateText: "Actualizar",
};
