import { color } from "@mui/system";
import colorCodes from "./colors";

let theme = {
  defaultTheme: {
    palette: {
      sidebar: {
        sidebarBg: colorCodes.darkBlackShade,
        menuColor: colorCodes?.orangeDarkShades,
      },
      notification: {
        notificationBg: colorCodes?.darkBlack,
        notificationBoxShadow: colorCodes?.notificationPanelShadowColor,
        listItemBorder: colorCodes?.darkGreyBalckShade,
        listItemLabel: colorCodes.greyColor,
        listItemLabelSelected: colorCodes.tabSelectedOrange,
        listItemLabelSelectedBtn: colorCodes.orangeShadeRed,
        tabListCountColor: colorCodes?.greyColor2,
        listItemContent: colorCodes.colorWhite,
        collapsedListItemTextColor: colorCodes.colorWhite,
        notificationPanelTitle: colorCodes?.colorWhite,
        expansionListItemBg: colorCodes?.notificationCalloutBg,
        expansionMarkerListBg: colorCodes?.notificationMarkerCalloutBg,
        dashBoardexpansionMarkerListBg:
          colorCodes?.dashBoardNotificationMarkerCalloutBg,
        expansionListItemBorder: colorCodes?.tabSelectedOrange,
        listItemBg: colorCodes?.darkBlackShade,
        eventColor: colorCodes?.green,
        oprAlertColor: colorCodes?.orange,
        incidentColor: colorCodes?.red,
        colorWhite: colorCodes?.colorWhite,
        noResultFoundColor: colorCodes?.colorWhite,
        notiTabBottomBorder: colorCodes?.whiteFade,
      },
      login: {
        boxTopLineStyle: colorCodes?.orngeLinearGradient,
      },
      gridViewPage: {
        gridPageBg: colorCodes?.blackShades,
        gridBorderColor: colorCodes?.blueShades,
        commonTextColor: colorCodes?.whiteShades2,
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.shadesOfBlueGreen,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.colorWhite,
        verticalBarLabelColor: colorCodes?.silverGray,
        todayTitleTextColor: colorCodes?.greenColorShades,
        todayTitleBgColor: "unset",
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },

      chart: {
        xAxisTextColor: colorCodes?.colorWhite,
      },
      flippingCard: {
        background: colorCodes?.flippingCardBgDark,
        textColor: colorCodes?.flippingCardDarkTextColor,
      },
      fleetManagementPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        securityProgressBarBg: colorCodes?.darkGrayBrownShade,
        circularProgressBar: {
          background: colorCodes?.iconBackgroundDark,
          stokeColorGreen: colorCodes?.speedometerGreen,
          stokeColorRed: colorCodes?.speedometerRed,
          track: colorCodes?.speedometerTrackDark,
        },
      },
      parkingPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkBlackShade,
        liveContentDividerLineColor : colorCodes?.colorWhite,
        progressTrailColor: colorCodes?.darkGrayBrownShade,
        parkingSlotBgColor : colorCodes?.darkGrayLightOpacity,
        topPanelContainerBg : colorCodes?.blackShades,
      },
      footer: {
        footerBg: colorCodes?.blackGrayShades,
        footerTextColor: colorCodes?.whiteGrayShades,
      },
      assetTrackingPage: {
        pageBg: colorCodes?.darkGrey1,
        topPanelBorder: "",
        topPanelBg: colorCodes?.notificationCalloutBg,
        topPanelCenterBg: colorCodes?.darkGrey2,
        topPanelTextColor: colorCodes?.colorWhite,
        topPanelSubTextColor: colorCodes?.colorWhite,
        geofenceListBorder: colorCodes?.mdGray,
        geofenceListBg: colorCodes?.darkBlack,
        geofenceListItemBg: colorCodes?.darkGrey2,
        geofenceTabBg: colorCodes?.darkBlackShade,
        geofenceTypeTextColor: colorCodes?.orange1,
        geofenceRestBtnColor: colorCodes?.darkBlackShade,
        geofenceAssetsBg: colorCodes?.darkGrey3,
        selectBg: colorCodes?.darkBlackShade,
      },
      energyMgmtPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkBlackShade,
        liveContentDividerLineColor : colorCodes?.colorWhite,
        progressTrailColor: colorCodes?.darkGrayBrownShade,
        parkingSlotBgColor : colorCodes?.darkGrayLightOpacity,
        topPanelContainerBg : colorCodes?.blackShades,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  lightTheme: {
    palette: {
      sidebar: {
        sidebarBg: colorCodes.sunRiseOrange,
        menuColor: colorCodes?.colorWhite,
      },
      notification: {
        notificationBg: colorCodes?.lightWhite,
        notificationBoxShadow: colorCodes?.notificationPanelShadowColor,
        listItemBorder: colorCodes.colorWhite,
        listItemLabel: colorCodes?.mdGray,
        listItemLabelSelected: colorCodes?.tabSelectedOrange,
        listItemLabelSelectedBtn: colorCodes?.tabSelectedOrangeLight,
        tabListCountColor: colorCodes?.colorWhite,
        listItemContent: colorCodes.colorWhite,
        collapsedListItemTextColor: colorCodes.darkBlackShade,
        notificationPanelTitle: colorCodes?.darkBlackShade,
        expansionListItemBg: colorCodes?.notificationExpandedBgLight,
        expansionMarkerListBg: colorCodes?.notificationExpandedBgLight,
        dashBoardexpansionMarkerListBg:
          colorCodes?.dashBoardNotificationMarkerCalloutBgLight,
        expansionListItemBorder: colorCodes?.tabSelectedOrangeLight,
        listItemBg: colorCodes?.mdGray,
        eventColor: colorCodes?.green,
        oprAlertColor: colorCodes?.orange,
        incidentColor: colorCodes?.red,
        colorWhite: colorCodes?.colorWhite,
        noResultFoundColor: colorCodes?.colorBlack,
        notiTabBottomBorder: colorCodes?.grayFade,
      },
      flippingCard: {
        background: colorCodes?.flippingCardBgLight,
        textColor: colorCodes?.darkBlackShade,
      },
      login: {
        boxTopLineStyle: colorCodes?.orngeLinearGradient,
      },
      gridViewPage: {
        gridPageBg: colorCodes?.whiteShades,
        gridBorderColor: colorCodes?.redShades,
        commonTextColor: colorCodes?.darkBlackShade,
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.darkBlackShade,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.darkBlackShade,
        verticalBarLabelColor: colorCodes?.mdGray,
        todayTitleTextColor: colorCodes?.redColorShades,
        todayTitleBgColor: colorCodes?.redColorShades2,
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },
      chart: {
        xAxisTextColor: colorCodes?.mdGray,
      },
      footer: {
        footerBg: colorCodes?.grayBlackShades,
        footerTextColor: colorCodes?.grayWhiteShades,
      },
      fleetManagementPage: {
        pageBg: colorCodes?.whiteColor,
        topPanelBorder: colorCodes?.mdGray,
        topPanelTextColor: colorCodes?.darkBlackShade,
        infoDialogColor: colorCodes?.colorWhite,
        routeDetailsBg: colorCodes?.whiteColor1,
        routeDetailsTitle: colorCodes?.darkBlackShade,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar2,
        violationBg: colorCodes?.lightWhite,
        violationListBg: colorCodes?.colorWhite,
        violationListTextColor: colorCodes?.darkBlackShade,
        violationListSubTextColor: colorCodes?.mdGray,
        circularProgressBar: {
          background: colorCodes?.colorWhite,
          stokeColorGreen: colorCodes?.speedometerGreen,
          stokeColorRed: colorCodes?.speedometerRed,
          track: colorCodes?.speedometerTrackLight,
        },
        listItemsBorder: "",
        graphBg: colorCodes?.whiteColor1,
        securityProgressBarBg: colorCodes?.blueShadesOfProgressBar,
      },
      assetTrackingPage: {
        pageBg: colorCodes?.colorWhite,
        topPanelBorder: colorCodes?.mdGray,
        topPanelBg: colorCodes?.whiteColor1,
        topPanelCenterBg: colorCodes?.whiteColor1,
        topPanelTextColor: colorCodes?.darkBlackShade,
        topPanelSubTextColor: colorCodes?.mdGray,
        geofenceListBorder: "",
        geofenceListBg: colorCodes?.whiteColor2,
        geofenceListItemBg: colorCodes?.colorWhite,
        geofenceTabBg: colorCodes?.whiteColor3,
        geofenceTypeTextColor: colorCodes?.darkBlackShade,
        geofenceRestBtnColor: colorCodes?.mdGray,
        geofenceAssetsBg: colorCodes?.lightWhite,
        selectBg: colorCodes?.colorWhite,
      },
      parkingPage: {
        pageBg: colorCodes?.lightGrayLightWhiteShade,
        topPanelBorder: colorCodes?.darkGrayLightShade,
        topPanelTextColor: colorCodes?.darkBlackShade,
        infoDialogColor: colorCodes?.colorWhite,
        routeDetailsBg: colorCodes?.whiteColor1,
        routeDetailsTitle: colorCodes?.darkBlackShade,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar2,
        violationBg: colorCodes?.lightWhite,
        violationListBg: colorCodes?.colorWhite,
        violationListTextColor: colorCodes?.darkBlackShade,
        violationListSubTextColor: colorCodes?.mdGray,
        listItemsBorder: "",
        graphBg: colorCodes?.whiteColor1,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkGrayLightShade,
        liveContentDividerLineColor : colorCodes?.darkBlackShade,
        progressTrailColor: colorCodes?.lightOrangelightShade,
        parkingSlotBgColor : colorCodes?.lightGrayLightOpacity,
        topPanelContainerBg : colorCodes?.colorWhite,
      },
      energyMgmtPage: {
        pageBg: colorCodes?.lightGrayLightWhiteShade,
        topPanelBorder: colorCodes?.darkGrayLightShade,
        topPanelTextColor: colorCodes?.darkBlackShade,
        infoDialogColor: colorCodes?.colorWhite,
        routeDetailsBg: colorCodes?.whiteColor1,
        routeDetailsTitle: colorCodes?.darkBlackShade,
        progressBarBg: colorCodes?.progressBar1,
        dialogProgressBarBg: colorCodes?.progressBar2,
        violationBg: colorCodes?.lightWhite,
        violationListBg: colorCodes?.colorWhite,
        violationListTextColor: colorCodes?.darkBlackShade,
        violationListSubTextColor: colorCodes?.mdGray,
        listItemsBorder: "",
        graphBg: colorCodes?.whiteColor1,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkGrayLightShade,
        liveContentDividerLineColor : colorCodes?.darkBlackShade,
        progressTrailColor: colorCodes?.lightGreenWhiteShade,
        parkingSlotBgColor : colorCodes?.lightGrayLightOpacity,
        topPanelContainerBg : colorCodes?.colorWhite,
      },
    },

    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  darkTheme: {
    palette: {
      sidebar: {
        sidebarBg: colorCodes.colorBlack,
        menuColor: colorCodes?.orangeDarkShades,
      },
      notification: {
        notificationBg: colorCodes?.darkBlack,
        notificationBoxShadow: colorCodes?.notificationPanelShadowColor,
        listItemBorder: colorCodes?.darkGreyBalckShade,
        listItemLabel: colorCodes.greyColor,
        listItemLabelSelected: colorCodes.tabSelectedOrange,
        listItemLabelSelectedBtn: colorCodes.orangeShadeRed,
        tabListCountColor: colorCodes?.greyColor2,
        listItemContent: colorCodes.colorWhite,
        collapsedListItemTextColor: colorCodes.colorWhite,
        notificationPanelTitle: colorCodes?.colorWhite,
        expansionListItemBg: colorCodes?.notificationCalloutBg,
        expansionMarkerListBg: colorCodes?.notificationMarkerCalloutBg,
        dashBoardexpansionMarkerListBg:
          colorCodes?.dashBoardNotificationMarkerCalloutBg,
        expansionListItemBorder: colorCodes?.tabSelectedOrange,
        listItemBg: colorCodes?.darkBlackShade,
        eventColor: colorCodes?.green,
        oprAlertColor: colorCodes?.orange,
        incidentColor: colorCodes?.red,
        colorWhite: colorCodes?.colorWhite,
        noResultFoundColor: colorCodes?.colorWhite,
        notiTabBottomBorder: colorCodes?.whiteFade,
      },
      flippingCard: {
        background: colorCodes?.flippingCardBgDark,
        textColor: colorCodes?.flippingCardDarkTextColor,
      },
      login: {
        boxTopLineStyle: colorCodes?.orngeLinearGradient,
      },
      gridViewPage: {
        gridPageBg: colorCodes?.blackShades,
        gridBorderColor: colorCodes?.blueShades,
        commonTextColor: colorCodes?.whiteShades2,
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.shadesOfBlueGreen,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.colorWhite,
        verticalBarLabelColor: colorCodes?.silverGray,
        todayTitleTextColor: colorCodes?.greenColorShades,
        todayTitleBgColor: "unset",
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },
      chart: {
        xAxisTextColor: colorCodes?.colorWhite,
      },
      footer: {
        footerBg: colorCodes?.blackGrayShades,
        footerTextColor: colorCodes?.whiteGrayShades,
      },
      fleetManagementPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        securityProgressBarBg: colorCodes?.darkGrayBrownShade,
        circularProgressBar: {
          background: colorCodes?.iconBackgroundDark,
          stokeColorGreen: colorCodes?.speedometerGreen,
          stokeColorRed: colorCodes?.speedometerRed,
          track: colorCodes?.speedometerTrackDark,
        },
      },
      assetTrackingPage: {
        pageBg: colorCodes?.darkGrey1,
        topPanelBorder: "",
        topPanelBg: colorCodes?.notificationCalloutBg,
        topPanelCenterBg: colorCodes?.darkGrey2,
        topPanelTextColor: colorCodes?.colorWhite,
        topPanelSubTextColor: colorCodes?.colorWhite,
        geofenceListBorder: colorCodes?.mdGray,
        geofenceListBg: colorCodes?.darkBlack,
        geofenceListItemBg: colorCodes?.darkGrey2,
        geofenceTabBg: colorCodes?.darkBlackShade,
        geofenceTypeTextColor: colorCodes?.orange1,
        geofenceRestBtnColor: colorCodes?.darkBlackShade,
        geofenceAssetsBg: colorCodes?.darkGrey3,
        selectBg: colorCodes?.darkBlackShade,
      },
      parkingPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkBlackShade,
        liveContentDividerLineColor : colorCodes?.colorWhite,
        progressTrailColor: colorCodes?.darkGrayBrownShade,
        parkingSlotBgColor : colorCodes?.darkGrayLightOpacity,
        topPanelContainerBg : colorCodes?.blackShades,
      },
      energyMgmtPage: {
        pageBg: colorCodes?.blackShades,
        topPanelBorder: colorCodes?.darkBlackShade,
        topPanelTextColor: colorCodes?.whiteShades2,
        infoDialogColor: colorCodes?.darkGrey1,
        routeDetailsBg: colorCodes?.blackShades,
        routeDetailsTitle: colorCodes?.colorWhite,
        progressBarBg: colorCodes?.progressBar,
        dialogProgressBarBg: colorCodes?.progressBar,
        violationBg: colorCodes?.blackShades,
        violationListBg: colorCodes?.darkGrey2,
        violationListTextColor: colorCodes?.colorWhite,
        violationListSubTextColor: colorCodes?.colorWhite,
        listItemsBorder: colorCodes?.mdGray,
        graphBg: colorCodes?.blackShades,
        sectionBorderColor : colorCodes?.darkBlackShade,
        topPanelBgColor : colorCodes?.darkBlackShade,
        liveContentDividerLineColor : colorCodes?.colorWhite,
        progressTrailColor: colorCodes?.darkGrayBrownShade,
        parkingSlotBgColor : colorCodes?.darkGrayLightOpacity,
        topPanelContainerBg : colorCodes?.blackShades,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
};
export default theme;
