import { color } from "@mui/system";
import colorCodes from "./colors";

let theme = {
  defaultTheme: {
    palette: {
      login: {
        loginBannerTitle: colorCodes.colorWhite,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.orangeTwo,
        loginBoxId: colorCodes.lightSkyBlue,
        textColor: colorCodes.lightGrey2,
        boxShadow: colorCodes.rgbaOne,
        inputTitle: colorCodes.orangeTwo,
        loginBg: colorCodes.linearBackgroundOne,
        loginBorder: colorCodes.lightGreyinputBorder
      },
      sidebar: {
        menuActiveColor: colorCodes.orangeOne,
        menuColor: colorCodes.darkGreyBlueOne,
        sidebarBg: colorCodes.darkGreyBlueTwo,
        avatharColor: colorCodes.colorWhite,
      },
      googleMap: {
        mapBgColor: colorCodes.darkBlue,
        roadColor: colorCodes.lightGrey1,
        textColor: colorCodes.darkGrey,
        riverColor: colorCodes.blueBlack,
      },
      notification: {
        notificationBg: colorCodes?.linearGradientBackground,
        notificationBoxShadow: colorCodes?.linearGradientTwo,
        listItemBg: colorCodes?.darkBlackShade,
        listItemBorder: colorCodes?.darkGreyBalckShade,
        eventColor: colorCodes?.greenColor,
        incidentColor: colorCodes?.redColor,
        oprAlertColor: colorCodes?.orangeColor,
        tabTextColor: colorCodes?.greyColor,
        takeActionButtonColor: colorCodes?.orangeShadeRed,
        listTextColor: colorCodes?.colorWhite,
        tabListCountColor: colorCodes?.greyColor2,
        expansionListItemBorder : colorCodes?.darkOrangeShade
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.shadesOfBlueGreen,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.colorWhite,
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,        
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },
    },

    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  lightTheme: {
    palette: {
      login: {
        loginBannerTitle: colorCodes.colorWhite,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.orangeTwo,
        loginBoxId: colorCodes.lightSkyBlue,
        textColor: colorCodes.lightGrey2,
        boxShadow: colorCodes.rgbaOne,
        inputTitle: colorCodes.orangeTwo,
        loginBg: colorCodes.linearBackgroundOne,
        loginBorder: colorCodes.lightGreyinputBorder
      },
      sidebar: {
        menuActiveColor: colorCodes.orangeOne,
        menuColor: colorCodes.darkGreyBlueOne,
        sidebarBg: colorCodes.darkGreyBlueTwo,
        avatharColor: colorCodes.colorWhite,
      },
      googleMap: {
        mapBgColor: colorCodes.darkBlue,
        roadColor: colorCodes.lightGrey1,
        textColor: colorCodes.darkGrey,
        riverColor: colorCodes.blueBlack,
      },
      notification: {
        notificationBg: colorCodes?.linearGradientBackground,
        notificationBoxShadow: colorCodes?.linearGradientTwo,
        listItemBg: colorCodes?.darkBlackShade,
        listItemBorder: colorCodes?.darkGreyBalckShade,
        eventColor: colorCodes?.greenColor,
        incidentColor: colorCodes?.redColor,
        oprAlertColor: colorCodes?.orangeColor,
        tabTextColor: colorCodes?.greyColor,
        takeActionButtonColor: colorCodes?.orangeShadeRed,
        listTextColor: colorCodes?.colorWhite,
        tabListCountColor: colorCodes?.greyColor2,
        expansionListItemBorder : colorCodes?.darkOrangeShade
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.shadesOfBlueGreen,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.colorWhite,
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,        
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },
    },

    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  darkTheme: {
    palette: {
      login: {
        loginBannerTitle: colorCodes.colorBlack,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.orangeTwo,
        loginBoxId: colorCodes.colorWhite,
        textColor: colorCodes.lightGrey2,
        boxShadow: colorCodes.rgbaOne,
        inputTitle: colorCodes.orangeTwo,
        loginBg: colorCodes.linearBackgroundOne,
        loginBorder: colorCodes.lightGreyinputBorder
      },
      sidebar: {
        menuActiveColor: colorCodes.orangeOne,
        menuColor: colorCodes.darkGreyBlueOne,
        sidebarBg: colorCodes.darkGreyBlueTwo,
        avatharColor: colorCodes.colorWhite,
      },
      googleMap: {
        mapBgColor: colorCodes.darkBlue,
        roadColor: colorCodes.lightGrey1,
        textColor: colorCodes.darkGrey,
        riverColor: colorCodes.blueBlack,
      },
      notification: {
        notificationBg: colorCodes?.linearGradientBackground,
        notificationBoxShadow: colorCodes?.linearGradientTwo,
        listItemBg: colorCodes?.darkBlackShade,
        listItemBorder: colorCodes?.darkGreyBalckShade,
        eventColor: colorCodes?.greenColor,
        incidentColor: colorCodes?.redColor,
        oprAlertColor: colorCodes?.orangeColor,
        tabTextColor: colorCodes?.greyColor,
        takeActionButtonColor: colorCodes?.orangeShadeRed,
        listTextColor: colorCodes?.colorWhite,
        tabListCountColor: colorCodes?.greyColor2,
        expansionListItemBorder : colorCodes?.darkOrangeShade
      },
      gridViewComponentCommonStyle: {
        containerTitle: colorCodes.vibrantOrangeColor,
        liveContainerBg: colorCodes.darkBluish,
        liveContentValueGreen: colorCodes.vibrantShadeOfGreen,
        lastweekTitle: colorCodes.greenishBlue,
        horizantalDataGridLabel: colorCodes.silverGray,
        rightListItemBorder: colorCodes.shadesOfBlueGreen,
        aqiCircleBg: colorCodes.shadeOfYellowishGreen,
        aqiCircleShadow: colorCodes.semiTransparentLimeGreen,
        liveContentLeftBorder: colorCodes.colorWhite,
      },
      gridViewPageStyle: {
        rootContainerBg: colorCodes.deepBlue,
        mainSectionGridBg: colorCodes.charCoalBlack,
        mainSectionGridBorder: colorCodes.navyBlue,        
      },
      gridViewComponentGraphsColor: {
        screenOneGraphLine: colorCodes.vibrantBlueGreenOpacity,
        screenOneGraphPoint: colorCodes.vibrantBlueGreen,
        screenTwoGraph1Line: colorCodes.goldenYellowOpacity,
        screenTwoGraph1Point: colorCodes.goldenYellow,
        screenTwoGraph2Line: colorCodes.limeGreenOpacity,
        screenTwoGraph2Point: colorCodes.limeGreen,
        screenTwoGraph3Line: colorCodes.electricBlueOpacity,
        screenTwoGraph3Point: colorCodes.electricBlue,
        screenThreeGraphLine: colorCodes.cyanBlueGreenOpacity,
        screenThreeGraphPoint: colorCodes.cyanBlueGreen,
        screenFourStrockColor: colorCodes.tealBlueGreen,
        screenFourTrackStrokeColor: colorCodes.semiTransparentWhite,
        screenFiveStrockColor1: colorCodes.oliveGreen,
        screenFiveTrackStrokeColor1: colorCodes.semiTransparentWhite,
        screenFiveStrockColor2: colorCodes.seaGreen,
        screenFiveTrackStrokeColor2: colorCodes.semiTransparentWhite,
        screenSixGraphLine: colorCodes.turquoiseBlueGreenOpacity,
        screenSixGraphPoint: colorCodes.turquoiseBlueGreen,
        highChartsGradient: colorCodes.colorBlack,
      },
    },

    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
};

export default theme;
