import { color } from "@mui/system";
import colorCodes from "./colors";

let theme = {
  defaultTheme: {
    palette: {
      login: {
        pageBackgroundColor: colorCodes.colorGreenTwo,
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorWhite,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.darkGreyOne,
        loginFormTitle: colorCodes.darkGreyTwo,
        inputTitleColor: colorCodes.lightGrey4,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.colorBlue,
        loginBoxId: colorCodes.lightSkyBlue,
        loginTextColor: colorCodes.lightGrey1,
        textColor: colorCodes.lightGrey2,
      },
      dashboard: {
        pageBackgroundColor: colorCodes.colorGreenTwo,
        dashboardLeftPanBg: colorCodes.lightBlueOne,
        listBoxBg: colorCodes.colorWhite,
        listBoxBorder: colorCodes.lightGrey3,
        boxShadow: colorCodes.rgbaOne,
        textColor: colorCodes.darkGrey,
        subTitle: colorCodes.lightGrey7,
        boxBorder: colorCodes.lightGrey3,
        subTitle2: colorCodes.darkGrey2,
        dashboardBg: colorCodes.lightBlueOne,
      },
      profile: { pageBackgroundColor: colorCodes.colorGreenTwo },
      infoDialogue: {
        headerSubTitleColor: colorCodes.darkGreyThree,
        headerSubTitleColor2: colorCodes.rgbaFour,
        infocustomNotificationTabs: colorCodes.lightGrey5,
        infocustomNotificationTabSelected: colorCodes.colorBlue,
        infoDividerLine: colorCodes.lightBlue,
        closeBtnColorAndDialogueBg: colorCodes.colorWhite,
        dialogueMuiPapercolor: colorCodes.colorBlack,
        dialogueBackDropBg: colorCodes.darkNavyBlue,
      },
      infoDialogueTrackerHistory: {
        historyListItemContainerBg: colorCodes.colorWhite,
        historyListItemTopContainerDivider: colorCodes.rgbaSix,
        historyListContainerBorder: colorCodes.lightGrey3,
        historyListContainerBoxShadow: colorCodes.transparentBlack,
        subTitle2: colorCodes.darkGrey2,
        listAreaTextColor: colorCodes?.darkGrey,
        listAreaTextColor2: colorCodes.lightGrey17,
        listAreaTextColor3: colorCodes.lightGrey14,
      },
      infoSubList: {
        iconBg: colorCodes.paleBlue,
        infoSubListBg: colorCodes.babyBlue,
        infoSubTitle: colorCodes.lightGrey14,
        infoSubTitle2: colorCodes.darkGrey3,
      },
      infoDialogueTrackerTable: {
        tableCellHeadColor: colorCodes.colorWhite,
        tableCellHeadBg: colorCodes.colorBlue,
        tableCellBodyColor: colorCodes.darkBluishGrayShade,
        tableBorderColor: colorCodes.palePurplishBlue,
        tableTextHeadering: colorCodes.lightGrey4,
        tableTextInputTitle: colorCodes.darkGreyOne,
        tableTextinputTitle2: colorCodes.lightGrey18,
      },
      sidebar: {
        sidebarBg: colorCodes.colorBlue,
        footerBg: colorCodes.colorWhite,
        sideBarBorder: colorCodes.lightBlueOne,
        toolTip: colorCodes.colorBlack,
      },
      tracker: {
        trackerBg: colorCodes.darkGrey5,
        trackerBg2: colorCodes.darkBlue3,
        trackerBg3: colorCodes.colorWhite,
        trackerButton: colorCodes.colorBlue,
        searchBg: colorCodes.lightGrey6,
        searchColor: colorCodes.rgbaTwo,
        searchBorder: colorCodes.lightGrey12,
        searchColor2: colorCodes.darkGrey7,
        trackerBorderColor: colorCodes.rgbaSeven,
        trackerBorderColor2: colorCodes.rgbaEight,
        trackerTableBgHead: colorCodes.lightBlueFive,
        trackerBg4: colorCodes.lightBlueFour,
      },
      select: {
        selectBgOne: colorCodes.colorWhite,
        selectBgTwo: colorCodes.colorBlack,
      },

      header: {
        headerBg: colorCodes.colorWhite,
        boxShadow: colorCodes.rgbaOne,
        headerLogo: colorCodes.darkGrey3,
        subTitle3: colorCodes.darkGrey4,
        subTitle2: colorCodes.darkGrey2,
        iconBg: colorCodes.lightGrey9,
        menuBorder: colorCodes.lightGrey10,
        iconSection: colorCodes.lightGrey11,
      },
      dashboardLeftPanel: {
        background: colorCodes?.lightBlueOne,
        searchSvg: colorCodes?.colorBlue,
        boxShadow: colorCodes?.rgbaOne,
        eventColor: colorCodes?.colorGreen2,
        incidentColor: colorCodes?.colorOrange,
        opsAlertColor: colorCodes?.colorRed,
        drowpDownTextColor: colorCodes?.colorBlack,
        dropDownBgColor: colorCodes?.colorWhite,
        dropDownSelectedBgColor: colorCodes?.lightBlueOne,
        dropDownSelectedTextColor: colorCodes?.darkBlueOne,
        searchTextColor: colorCodes?.lightGrey9,
        listExpansionBackgroundColor: colorCodes?.colorWhite,
        buttonTextColor: colorCodes?.colorBlack,
        selectedButtonColor: colorCodes?.colorBlue,
        selectedButtonColor2: colorCodes?.colorWhite,
        cardTextColor: colorCodes.colorBlack,
        selectedButtonBgColor: colorCodes?.colorBlue,
        listAreaTextColor: colorCodes?.darkGrey,
        listLastUpdatedColor: colorCodes?.lightGrey7,
        listIconValue: colorCodes?.darkGrey2,
        expansionListBorder: colorCodes?.colorBlue,
        markerCloseIcon: colorCodes?.darkGrey10,
        chipButtonDefaultBg: colorCodes?.colorWhite,
        chipButtonBorder: colorCodes?.lightGrey14,
        chipButtonLabelSelected: colorCodes?.colorWhite,
        chipButtonLabelDefault: colorCodes?.darkGrey,
        chipBadgeDefaultBg: colorCodes?.lightGrey15,
        chipBadgeDefaultCount: colorCodes?.colorBlack,
        chipBadgeFocusedBg: colorCodes?.colorWhite,
        searchBgColor: colorCodes?.colorWhite,
        markerCloseIconBg: colorCodes?.colorWhite,
        infoIconValueColor: colorCodes?.darkBlue1,
        notificationInfoListSubTitle: colorCodes?.darkGrey5,
      },
      dashboardInfoIconContainer: {
        background: colorCodes?.colorWhite,
        infoIconValueColor: colorCodes?.darkBlue1,
        infoIconTitleColor: colorCodes?.lightBlack1,
      },
      infoDialogueConfigurationContainer: {
        configurationListContainerBg: colorCodes?.blueishGrayColor,
        minMaxBorderColor: colorCodes?.darkBlueShade,
        background: colorCodes?.colorWhite,
        configurationTitle: colorCodes.darkGrey10,
        configurationTitle2: colorCodes.lightGrey14,
        tableCellTitle: colorCodes.colorBlue,
      },
      geofence: {
        geofenceTitle: colorCodes.darkGrey8,
        geofenceInput: colorCodes.colorBlue,
        checkBoxTitle: colorCodes.darkGrey9,
        checkboxDisbaled: colorCodes.rgbaFive,
        geoFenceTitle2: colorCodes.lightGrey16,
      },
      addGroupTrackerDialogue: {
        headerSubTitle: colorCodes.colorBlue,
        selectDropDownBorder: colorCodes.lavenderBlush,
        inputBaseColor: colorCodes.darkGreyOne,
        inputBaseBorder: colorCodes.mediumPurple,
        selectedTagTextArea: colorCodes.transparentDarkGrayishBlue,
        background: colorCodes?.colorWhite,
        dropDownSelectedBg: colorCodes?.whiteLilac,
        configurationTitle3: colorCodes.darkGrey11,
        progressTitle: colorCodes.colorBlack,
        trackerTitle: colorCodes.darkBlue5,
        palletListDataBoarder: colorCodes.lightGrey14,
        palletListItemsBoarder: colorCodes.shadesDarkGray,
        palletListItemsBg: colorCodes.lavenderBlue,
      },
      textFieldElement: {
        textFieldBorder: colorCodes?.lightGrey14,
      },
      table: {
        trackerBg4: colorCodes.lightBlueFour,
        trackerTextColor: colorCodes.darkGrey12,
        trackerTextColor2: colorCodes.lightGrey18,
      },
      tab: {
        tabSection: colorCodes.colorWhite,
        tabSectionText: colorCodes.colorWhite,
        tabSectionText2: colorCodes.colorBlack,
        tabSectionText3: colorCodes.lightGrey5,
        selectedTabBg: colorCodes.colorBlue,
        selectedTabBg2: colorCodes.colorBlue,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  lightTheme: {
    palette: {
      login: {
        pageBackgroundColor: colorCodes.colorGreenThree,
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorWhite,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.darkGreyOne,
        loginFormTitle: colorCodes.darkGreyTwo,
        inputTitleColor: colorCodes.lightGrey4,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.colorBlue,
        loginBoxId: colorCodes.lightSkyBlue,
        loginTextColor: colorCodes.lightGrey3,
        textColor: colorCodes.lightGrey2,
      },
      dashboard: {
        pageBackgroundColor: colorCodes.colorGreenThree,
        dashboardLeftPanBg: colorCodes.lightBlueOne,
        listBoxBg: colorCodes.lightGrey3,
        listBoxBorder: colorCodes.lightGrey3,
        boxShadow: colorCodes.rgbaOne,
        textColor: colorCodes.lightGrey2,
        subTitle: colorCodes.lightGrey7,
        boxBorder: colorCodes.lightGrey3,
        subTitle2: colorCodes.darkGrey2,
        dashboardBg: colorCodes.lightBlueThree,
      },
      profile: { pageBackgroundColor: colorCodes.lightBlueThree },
      infoDialogue: {
        headerSubTitleColor: colorCodes.darkGreyThree,
        headerSubTitleColor2: colorCodes.rgbaFour,
        infocustomNotificationTabs: colorCodes.lightGrey5,
        infocustomNotificationTabSelected: colorCodes.colorBlue,
        infoDividerLine: colorCodes.lightBlue,
        closeBtnColorAndDialogueBg: colorCodes.lightGrey3,
        dialogueMuiPapercolor: colorCodes.colorBlack,
        dialogueBackDropBg: colorCodes.darkNavyBlue,
      },
      infoDialogueTrackerHistory: {
        historyListItemContainerBg: colorCodes.colorWhite,
        historyListItemTopContainerDivider: colorCodes.rgbaSix,
        historyListContainerBorder: colorCodes.lightGrey3,
        historyListContainerBoxShadow: colorCodes.transparentBlack,
        subTitle2: colorCodes.darkGrey2,
        listAreaTextColor: colorCodes?.darkGrey,
        listAreaTextColor2: colorCodes.lightGrey17,
        listAreaTextColor3: colorCodes.lightGrey14,
      },
      infoSubList: {
        iconBg: colorCodes.paleBlue,
        infoSubListBg: colorCodes.babyBlue,
        infoSubTitle: colorCodes.lightGrey14,
        infoSubTitle2: colorCodes.darkGrey3,
      },
      infoDialogueTrackerTable: {
        tableCellHeadColor: colorCodes.colorWhite,
        tableCellHeadBg: colorCodes.colorBlue,
        tableCellBodyColor: colorCodes.darkBluishGrayShade,
        tableBorderColor: colorCodes.palePurplishBlue,
        tableTextHeadering: colorCodes.lightGrey4,
        tableTextInputTitle: colorCodes.darkGreyOne,
        tableTextinputTitle2: colorCodes.lightGrey18,
      },
      sidebar: {
        sidebarBg: colorCodes.lightBlueTwo,
        footerBg: colorCodes.colorWhite,
        sideBarBorder: colorCodes.lightGrey11,
        toolTip: colorCodes.colorBlack,
      },
      tracker: {
        trackerBg: colorCodes.darkGrey5,
        trackerBg2: colorCodes.darkBlue3,
        trackerBg3: colorCodes.lightGrey3,
        trackerButton: colorCodes.colorBlue,
        searchBg: colorCodes.lightGrey6,
        searchColor: colorCodes.rgbaTwo,
        searchBorder: colorCodes.lightGrey12,
        searchColor2: colorCodes.darkGrey7,
        trackerBorderColor: colorCodes.rgbaSeven,
        trackerBorderColor2: colorCodes.rgbaEight,
        trackerTableBgHead: colorCodes.lightBlueFive,
        trackerBg4: colorCodes.lightBlueFour,
      },

      header: {
        headerBg: colorCodes.lightGrey11,
        boxShadow: colorCodes.rgbaOne,
        headerLogo: colorCodes.darkGrey3,
        subTitle3: colorCodes.darkGrey4,
        subTitle2: colorCodes.darkGrey2,
        iconBg: colorCodes.lightGrey12,
        menuBorder: colorCodes.lightGrey10,
        iconSection: colorCodes.lightGrey11,
      },
      dashboardLeftPanel: {
        background: colorCodes?.lightBlueThree,
        searchSvg: colorCodes?.colorBlue,
        boxShadow: colorCodes?.rgbaOne,
        eventColor: colorCodes?.colorGreen2,
        incidentColor: colorCodes?.colorOrange,
        opsAlertColor: colorCodes?.colorRed,
        drowpDownTextColor: colorCodes?.colorBlack,
        dropDownBgColor: colorCodes?.lightGrey3,
        dropDownSelectedBgColor: colorCodes?.lightBlueOne,
        dropDownSelectedTextColor: colorCodes?.darkBlueOne,
        searchTextColor: colorCodes?.lightGrey9,
        listExpansionBackgroundColor: colorCodes?.lightGrey3,
        buttonTextColor: colorCodes?.colorBlack,
        selectedButtonColor: colorCodes?.darkGrey2,
        selectedButtonColor2: colorCodes?.colorBlack,
        selectedButtonBgColor: colorCodes?.lightBlueThree,
        cardTextColor: colorCodes.colorBlack,
        listAreaTextColor: colorCodes?.darkGrey,
        listLastUpdatedColor: colorCodes?.lightGrey7,
        listIconValue: colorCodes?.darkGrey2,
        expansionListBorder: colorCodes?.colorBlue,
        markerCloseIcon: colorCodes?.darkGrey10,
        chipButtonDefaultBg: colorCodes?.colorWhite,
        chipButtonBorder: colorCodes?.lightGrey14,
        chipButtonLabelSelected: colorCodes?.colorWhite,
        chipButtonLabelDefault: colorCodes?.darkGrey,
        chipBadgeDefaultBg: colorCodes?.lightGrey15,
        chipBadgeDefaultCount: colorCodes?.colorBlack,
        chipBadgeFocusedBg: colorCodes?.colorWhite,
        searchBgColor: colorCodes?.colorWhite,
        markerCloseIconBg: colorCodes?.lightGrey3,
        infoIconValueColor: colorCodes?.darkBlue1,
        notificationInfoListSubTitle: colorCodes?.darkGrey8,
      },
      dashboardInfoIconContainer: {
        background: colorCodes?.colorWhite,
        infoIconValueColor: colorCodes?.darkBlue1,
        infoIconTitleColor: colorCodes?.lightBlack1,
      },
      select: {
        selectBgOne: colorCodes.colorWhite,
        selectBgTwo: colorCodes.colorBlack,
      },
      infoDialogueConfigurationContainer: {
        configurationListContainerBg: colorCodes?.blueishGrayColor,
        minMaxBorderColor: colorCodes?.darkBlueShade,
        background: colorCodes?.colorWhite,
        configurationTitle: colorCodes.darkGrey10,
        configurationTitle2: colorCodes.lightGrey14,
        tableCellTitle: colorCodes.colorBlue,
      },
      geofence: {
        geofenceTitle: colorCodes.darkGrey8,
        geofenceInput: colorCodes.colorBlue,
        checkBoxTitle: colorCodes.darkGrey9,
        checkboxDisbaled: colorCodes.rgbaFive,
        geoFenceTitle2: colorCodes.lightGrey16,
      },
      addGroupTrackerDialogue: {
        headerSubTitle: colorCodes.colorBlue,
        selectDropDownBorder: colorCodes.lavenderBlush,
        inputBaseColor: colorCodes.darkGreyOne,
        inputBaseBorder: colorCodes.mediumPurple,
        selectedTagTextArea: colorCodes.transparentDarkGrayishBlue,
        background: colorCodes?.colorWhite,
        dropDownSelectedBg: colorCodes?.whiteLilac,
        configurationTitle3: colorCodes.darkGrey11,
        progressTitle: colorCodes.colorBlack,
        trackerTitle: colorCodes.darkBlue5,
        palletListDataBoarder: colorCodes.lightGrey14,
        palletListItemsBoarder: colorCodes.shadesDarkGray,
        palletListItemsBg: colorCodes.lavenderBlue,
      },
      textFieldElement: {
        textFieldBorder: colorCodes?.lightGrey14,
      },
      table: {
        trackerBg4: colorCodes.lightBlueFour,
        trackerTextColor: colorCodes.darkGrey12,
        trackerTextColor2: colorCodes.lightGrey18,
      },
      tab: {
        tabSection: colorCodes.lightGrey3,
        tabSectionText: colorCodes.colorWhite,
        tabSectionText2: colorCodes.colorBlack,
        tabSectionText3: colorCodes.lightGrey5,
        selectedTabBg: colorCodes.lightBlueTwo,
        selectedTabBg2: colorCodes.colorBlue,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
  darkTheme: {
    palette: {
      login: {
        pageBackgroundColor: colorCodes.lightYellow,
        loginBtnColor: "",
        titleColor: "",
        forgotPwdColor: "",
        loginBannerTitle: colorCodes.colorBlack,
        loginFormBg: colorCodes.colorWhite,
        loginBannerDescription: colorCodes.colorWhite,
        welcomeContent: colorCodes.darkGreyOne,
        loginFormTitle: colorCodes.darkGreyTwo,
        inputTitleColor: colorCodes.lightGrey4,
        inputPlaceholder: colorCodes.lightGrey13,
        copyRight: colorCodes.colorBlack,
        loginButton: colorCodes.colorBlue,
        loginBoxId: colorCodes.colorWhite,
        loginTextColor: colorCodes.darkGrey13,
        textColor: colorCodes.lightGrey2,
      },
      dashboard: {
        pageBackgroundColor: colorCodes.lightYellow,
        dashboardLeftPanBg: colorCodes.lightBlueOne,
        listBoxBg: colorCodes.darkGrey13,
        listBoxBorder: colorCodes.lightGrey3,
        boxShadow: colorCodes.rgbaOne,
        textColor: colorCodes.darkGreyOne,
        subTitle: colorCodes.lightGrey7,
        boxBorder: colorCodes.lightGrey3,
        subTitle2: colorCodes.darkGrey2,
        dashboardBg: colorCodes.darkGrey14,
      },
      profile: { pageBackgroundColor: colorCodes.darkBlue4 },
      infoDialogue: {
        headerSubTitleColor: colorCodes.colorWhite,
        headerSubTitleColor2: colorCodes.lightGrey5,
        infocustomNotificationTabs: colorCodes.colorWhite,
        infocustomNotificationTabSelected: colorCodes.colorWhite,
        infoDividerLine: colorCodes.lightBlue,
        closeBtnColorAndDialogueBg: colorCodes.darkGrey14,
        dialogueMuiPapercolor: colorCodes.colorBlack,
        dialogueBackDropBg: colorCodes.darkNavyBlue,
      },
      infoDialogueTrackerHistory: {
        historyListItemContainerBg: colorCodes.darkGrey13,
        historyListItemTopContainerDivider: colorCodes.rgbaSix,
        historyListContainerBorder: colorCodes.lightGrey3,
        historyListContainerBoxShadow: colorCodes.transparentBlack,
        subTitle2: colorCodes.colorWhite,
        listAreaTextColor: colorCodes?.darkGrey,
        listAreaTextColor2: colorCodes.lightGrey17,
        listAreaTextColor3: colorCodes.lightGrey14,
      },
      infoSubList: {
        iconBg: colorCodes.paleBlue,
        infoSubListBg: colorCodes.darkGrey13,
        infoSubTitle: colorCodes.colorWhite,
        infoSubTitle2: colorCodes.lightGrey5,
      },
      infoDialogueTrackerTable: {
        tableCellHeadColor: colorCodes.colorBlack,
        tableCellHeadBg: colorCodes.colorWhite,
        tableCellBodyColor: colorCodes.colorWhite,
        tableBorderColor: colorCodes.palePurplishBlue,
        tableTextHeadering: colorCodes.lightGrey4,
        tableTextInputTitle: colorCodes.colorWhite,
        tableTextinputTitle2: colorCodes.lightGrey18,
      },
      sidebar: {
        sidebarBg: colorCodes.darkBlue2,
        footerBg: colorCodes.colorWhite,
        sideBarBorder: colorCodes.darkGrey9,
        toolTip: colorCodes.colorBlack,
      },
      tracker: {
        trackerBg: colorCodes.darkGrey6,
        trackerBg2: colorCodes.colorWhite,
        trackerBg3: colorCodes.colorWhite,
        trackerButton: colorCodes.darkGrey15,
        searchBg: colorCodes.lightGrey6,
        searchColor: colorCodes.darkGrey13,
        searchBorder: colorCodes.lightGrey12,
        searchColor2: colorCodes.darkGrey7,
        trackerBorderColor: colorCodes.rgbaSeven,
        trackerBorderColor2: colorCodes.rgbaEight,
        trackerTableBgHead: colorCodes.lightBlueFive,
        trackerBg4: colorCodes.lightBlueFour,
      },

      header: {
        headerBg: colorCodes.darkGrey13,
        boxShadow: colorCodes.rgbaOne,
        headerLogo: colorCodes.colorWhite,
        subTitle3: colorCodes.darkGrey4,
        subTitle2: colorCodes.colorWhite,
        iconBg: colorCodes.lightBlueFive,
        menuBorder: colorCodes.lightGrey10,
        iconSection: colorCodes.lightGrey11,
      },
      dashboardLeftPanel: {
        background: colorCodes?.darkGrey14,
        searchSvg: colorCodes?.filterOne,
        boxShadow: colorCodes?.rgbaOne,
        eventColor: colorCodes?.colorGreen2,
        incidentColor: colorCodes?.colorOrange,
        opsAlertColor: colorCodes?.colorRed,
        drowpDownTextColor: colorCodes?.colorBlack,
        dropDownBgColor: colorCodes?.darkGrey13,
        dropDownSelectedBgColor: colorCodes?.lightBlueOne,
        dropDownSelectedTextColor: colorCodes?.darkBlueOne,
        searchTextColor: colorCodes?.lightGrey9,
        listExpansionBackgroundColor: colorCodes?.darkGrey13,
        buttonTextColor: colorCodes?.colorWhite,
        selectedButtonColor: colorCodes?.darkGrey15,
        selectedButtonColor2: colorCodes?.colorWhite,
        cardTextColor: colorCodes.colorWhite,
        selectedButtonBgColor: colorCodes?.darkGrey14,
        listAreaTextColor: colorCodes?.colorWhite,
        listLastUpdatedColor: colorCodes?.lightGrey7,
        listIconValue: colorCodes?.colorWhite,
        expansionListBorder: colorCodes?.colorBlue,
        markerCloseIcon: colorCodes?.darkGrey10,
        chipButtonDefaultBg: colorCodes?.colorWhite,
        chipButtonBorder: colorCodes?.lightGrey14,
        chipButtonLabelSelected: colorCodes?.colorWhite,
        chipButtonLabelDefault: colorCodes?.darkGrey,
        chipBadgeDefaultBg: colorCodes?.lightGrey15,
        chipBadgeDefaultCount: colorCodes?.colorBlack,
        chipBadgeFocusedBg: colorCodes?.colorWhite,
        searchBgColor: colorCodes?.colorWhite,
        markerCloseIconBg: colorCodes?.darkGrey13,
        infoIconValueColor: colorCodes?.colorWhite,
        notificationInfoListSubTitle: colorCodes?.darkGrey8,
      },
      dashboardInfoIconContainer: {
        background: colorCodes?.colorWhite,
        infoIconValueColor: colorCodes?.darkBlue1,
        infoIconTitleColor: colorCodes?.lightBlack1,
      },
      select: {
        selectBgOne: colorCodes.colorWhite,
        selectBgTwo: colorCodes.colorBlack,
      },
      infoDialogueConfigurationContainer: {
        configurationListContainerBg: colorCodes?.darkGrey13,
        minMaxBorderColor: colorCodes?.darkBlueShade,
        background: colorCodes?.colorWhite,
        configurationTitle: colorCodes.colorWhite,
        configurationTitle2: colorCodes.lightGrey14,
        tableCellTitle: colorCodes.colorBlue,
      },
      geofence: {
        geofenceTitle: colorCodes.colorWhite,
        geofenceInput: colorCodes.colorBlue,
        checkBoxTitle: colorCodes.darkGrey9,
        checkboxDisbaled: colorCodes.rgbaFive,
        geoFenceTitle2: colorCodes.colorWhite,
      },
      addGroupTrackerDialogue: {
        headerSubTitle: colorCodes.colorBlue,
        selectDropDownBorder: colorCodes.lavenderBlush,
        inputBaseColor: colorCodes.darkGreyOne,
        inputBaseBorder: colorCodes.mediumPurple,
        selectedTagTextArea: colorCodes.darkGrey13,
        background: colorCodes?.colorWhite,
        dropDownSelectedBg: colorCodes?.whiteLilac,
        configurationTitle3: colorCodes.colorWhite,
        progressTitle: colorCodes.colorBlack,
        trackerTitle: colorCodes.darkBlue5,
        palletListDataBoarder: colorCodes.lightGrey14,
        palletListItemsBoarder: colorCodes.shadesDarkGray,
        palletListItemsBg: colorCodes.lavenderBlue,
      },
      textFieldElement: {
        textFieldBorder: colorCodes?.lightGrey14,
      },
      table: {
        trackerBg4: colorCodes.darkGrey13,
        trackerTextColor: colorCodes.darkGrey12,
        trackerTextColor2: colorCodes.lightGrey18,
      },
      tab: {
        tabSection: colorCodes.darkGrey13,
        tabSectionText: colorCodes.colorWhite,
        tabSectionText2: colorCodes.colorWhite,
        tabSectionText3: colorCodes.lightGrey5,
        selectedTabBg: colorCodes.darkGrey15,
        selectedTabBg2: colorCodes.colorWhite,
      },
    },
    spacing: 5,
    typography: { fontFamily: "Arial" },
  },
};

export default theme;
